import{mountStudioV2}from'../../_shared/studio-v2/frame.js';
import{resolveStudioVersions}from'../../_shared/studio-v2/version-service.js';
import studioManifest from'./studio-manifest.js';
const VERSION_INFO=await resolveStudioVersions({versionsHref:'../versions.json',coreVersionHref:'../../_shared/studio-v2/version.json',channel:'test'});
await mountStudioV2({manifest:studioManifest,versionInfo:VERSION_INFO});
const $=s=>document.querySelector(s),editor=$('#editor'),preview=$('#preview');let fileName='nouveau.txt',format='txt';
const esc=s=>String(s??'').replace(/[&<>"]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[m]));
function render(){const t=editor.value;$('#words').textContent=(t.trim().match(/\S+/g)||[]).length;$('#chars').textContent=t.length;$('#lines').textContent=t?t.split(/\r?\n/).length:0;const q=$('#search').value.trim();preview.innerHTML=esc(t).replace(/\n/g,'<br>');if(q){const re=new RegExp(q.replace(/[.*+?^$()|[\]{}\\]/g,'\\$&'),'gi');preview.innerHTML=preview.innerHTML.replace(re,m=>'<mark>'+m+'</mark>')}}
function textFromXml(xml){const d=new DOMParser().parseFromString(xml,'application/xml');return[...d.querySelectorAll('p,h,text\\:p,text\\:h,w\\:p')].map(n=>{const ts=[...n.querySelectorAll('t,w\\:t,text\\:span')].map(x=>x.textContent).join('');return ts||n.textContent||''}).filter(Boolean).join('\n')}
async function readDocx(file){const z=await JSZip.loadAsync(file),x=await z.file('word/document.xml')?.async('string');if(!x)throw new Error('DOCX sans word/document.xml');return textFromXml(x)}
async function readOdt(file){const z=await JSZip.loadAsync(file),x=await z.file('content.xml')?.async('string');if(!x)throw new Error('ODT sans content.xml');return textFromXml(x)}
function rtfText(s){return s.replace(/\\par[d]?/g,'\n').replace(/\\'[0-9a-fA-F]{2}/g,'').replace(/\\[a-zA-Z]+-?\d* ?/g,'').replace(/[{}]/g,'').trim()}
async function openFile(file){fileName=file.name;const ext=(file.name.split('.').pop()||'').toLowerCase();format=ext;$('#docName').textContent=file.name;$('#formatBadge').textContent=ext.toUpperCase();if(ext==='doc')throw new Error('DOC binaire legacy : conversion préalable vers DOCX, ODT ou RTF recommandée.');if(ext==='docx')editor.value=await readDocx(file);else if(ext==='odt')editor.value=await readOdt(file);else{const t=await file.text();if(ext==='html'||ext==='htm')editor.value=new DOMParser().parseFromString(t,'text/html').body.textContent||'';else if(ext==='rtf')editor.value=rtfText(t);else editor.value=t}render();$('#status').textContent='Chargé · '+file.name+' · conversion structurelle'}
function dl(blob,name){const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
function stem(){return(fileName||'document').replace(/\.[^.]+$/,'')}
function docxP(t){return'<w:p><w:r><w:t xml:space="preserve">'+esc(t)+'</w:t></w:r></w:p>'}
async function makeDocx(){const z=new JSZip();z.file('[Content_Types].xml','<?xml version="1.0" encoding="UTF-8"?><Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types"><Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/><Default Extension="xml" ContentType="application/xml"/><Override PartName="/word/document.xml" ContentType="application/vnd.openxmlformats-officedocument.wordprocessingml.document.main+xml"/></Types>');z.folder('_rels').file('.rels','<?xml version="1.0" encoding="UTF-8"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="word/document.xml"/></Relationships>');z.folder('word').file('document.xml','<?xml version="1.0" encoding="UTF-8"?><w:document xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main"><w:body>'+editor.value.split(/\r?\n/).map(docxP).join('')+'<w:sectPr/></w:body></w:document>');return z.generateAsync({type:'blob',mimeType:'application/vnd.openxmlformats-officedocument.wordprocessingml.document'})}
async function makeOdt(){const z=new JSZip();z.file('mimetype','application/vnd.oasis.opendocument.text',{compression:'STORE'});z.folder('META-INF').file('manifest.xml','<?xml version="1.0" encoding="UTF-8"?><manifest:manifest xmlns:manifest="urn:oasis:names:tc:opendocument:xmlns:manifest:1.0"><manifest:file-entry manifest:full-path="/" manifest:media-type="application/vnd.oasis.opendocument.text"/><manifest:file-entry manifest:full-path="content.xml" manifest:media-type="text/xml"/></manifest:manifest>');z.file('content.xml','<?xml version="1.0" encoding="UTF-8"?><office:document-content xmlns:office="urn:oasis:names:tc:opendocument:xmlns:office:1.0" xmlns:text="urn:oasis:names:tc:opendocument:xmlns:text:1.0"><office:body><office:text>'+editor.value.split(/\r?\n/).map(x=>'<text:p>'+esc(x)+'</text:p>').join('')+'</office:text></office:body></office:document-content>');return z.generateAsync({type:'blob',mimeType:'application/vnd.oasis.opendocument.text'})}
$('#fileInput').onchange=e=>{const f=e.target.files?.[0];if(f)openFile(f).catch(err=>$('#status').textContent=err.message)};$('#openDocument').onclick=()=>$('#fileInput').click();editor.addEventListener('input',render);$('#search').addEventListener('input',render);
$('#exportTxt').onclick=()=>dl(new Blob([editor.value],{type:'text/plain;charset=utf-8'}),stem()+'.txt');
$('#exportMd').onclick=()=>dl(new Blob([editor.value],{type:'text/markdown;charset=utf-8'}),stem()+'.md');
$('#exportHtml').onclick=()=>dl(new Blob(['<!doctype html><meta charset="utf-8"><body><pre style="white-space:pre-wrap">'+esc(editor.value)+'</pre></body>'],{type:'text/html;charset=utf-8'}),stem()+'.html');
$('#exportDocx').onclick=async()=>dl(await makeDocx(),stem()+'.docx');$('#exportOdt').onclick=async()=>dl(await makeOdt(),stem()+'.odt');
$('#printPdf').onclick=()=>{const w=window.open('','_blank','noopener,noreferrer');if(!w)return $('#status').textContent='Fenêtre d’impression bloquée';w.document.write('<!doctype html><meta charset="utf-8"><title>'+esc(stem())+'</title><style>@page{margin:18mm}body{font:12pt/1.55 Arial;white-space:pre-wrap}</style><body>'+esc(editor.value).replace(/\n/g,'<br>')+'<script>onload=()=>print()<\/script></body>');w.document.close();$('#status').textContent='Impression ouverte · choisir Enregistrer au format PDF'};
document.addEventListener('studio-v2:action',e=>{const a=e.detail?.action,map={openDocument:'#openDocument',exportTxt:'#exportTxt',exportMd:'#exportMd',exportHtml:'#exportHtml',exportDocx:'#exportDocx',exportOdt:'#exportOdt',printPdf:'#printPdf'};const sel=map[a];if(sel)$(sel)?.click()});
render();window.__NLAB_DOCUMENT_STUDIO__={getText:()=>editor.value,openFile};
