import{mountStudioV2}from'../../_shared/studio-v2/frame.js';
import{resolveStudioVersions}from'../../_shared/studio-v2/version-service.js';
import{readWorkbook,workbookFromCsv,workbookFromJson,workbookToRows,rowsToObjects,toCsv,workbookBlob}from'../../_shared/studio-v2/tabular-service.js';
import{downloadBlob,downloadJson,downloadCsv}from'../../_shared/studio-v2/download-service.js';
import studioManifest from'./studio-manifest.js';
import{pushUndoRedo}from'../../_shared/studio-v2/undo-redo.js';
const VERSION_INFO=await resolveStudioVersions({versionsHref:'../versions.json',coreVersionHref:'../../_shared/studio-v2/version.json',channel:'test'});
await mountStudioV2({manifest:studioManifest,versionInfo:VERSION_INFO});
const $=s=>document.querySelector(s);let wb=XLSX.utils.book_new(),bookName='classeur.xlsx',rows=[],txnMute=false,lastView=null,viewTxnTimer=null;
function esc(s){return String(s??'').replace(/[&<>"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]))}
function sheetRows(){return workbookToRows(wb,$('#sheetSelect').value)}
function sheetState(){return{bookName,workbook:XLSX.write(wb,{bookType:'xlsx',type:'array'}),sheet:$('#sheetSelect').value,search:$('#search').value,delimiter:$('#delimiter').value,bom:$('#bom').checked}}
function publishSheetContext(source='spreadsheet-studio'){document.dispatchEvent(new CustomEvent('studio-v2:selection-change',{detail:{selection:[{name:bookName}],active:{name:bookName},scope:'workbook',kind:'spreadsheet',meta:{sheet:$('#sheetSelect').value,sheetCount:wb.SheetNames.length,search:$('#search').value,rows:rows.length},source}}))}
function restoreSheetState(st,source='undo-redo'){txnMute=true;bookName=st.bookName||bookName;wb=XLSX.read(st.workbook,{type:'array'});$('#bookName').textContent=bookName;syncSheets();if(st.sheet&&wb.SheetNames.includes(st.sheet))$('#sheetSelect').value=st.sheet;$('#search').value=st.search||'';$('#delimiter').value=st.delimiter||';';$('#bom').checked=st.bom!==false;render();lastView=sheetState();publishSheetContext(source);txnMute=false}
function transactSheet(label,before,after){pushUndoRedo({label,meta:{studio:'spreadsheet-studio'},undo:()=>restoreSheetState(before,'undo'),redo:()=>restoreSheetState(after,'redo')})}
function queueSheetViewTxn(label='Modifier la vue tableur'){if(txnMute)return;clearTimeout(viewTxnTimer);viewTxnTimer=setTimeout(()=>{const after=sheetState(),before=lastView;if(before&&(before.sheet!==after.sheet||before.search!==after.search||before.delimiter!==after.delimiter||before.bom!==after.bom))transactSheet(label,before,after);lastView=after;publishSheetContext('view')},220)}
function render(){const all=sheetRows(),q=$('#search').value.trim().toLowerCase();rows=q?all.filter((r,i)=>i===0||r.some(v=>String(v??'').toLowerCase().includes(q))):all;const cols=Math.max(0,...rows.map(r=>r.length));$('#dims').textContent=Math.max(0,rows.length-1)+' × '+cols;if(!rows.length){$('#tableWrap').innerHTML='<div class="statusBox">Feuille vide.</div>';return}$('#tableWrap').innerHTML='<table><thead><tr>'+rows[0].map(x=>'<th>'+esc(x)+'</th>').join('')+'</tr></thead><tbody>'+rows.slice(1,251).map(r=>'<tr>'+Array.from({length:cols},(_,i)=>'<td>'+esc(r[i]??'')+'</td>').join('')+'</tr>').join('')+'</tbody></table>'}
function syncSheets(){const names=wb.SheetNames||[];$('#sheetSelect').innerHTML=names.map(n=>'<option value="'+esc(n)+'">'+esc(n)+'</option>').join('');render()}
async function openFile(file){const before=sheetState();bookName=file.name;$('#bookName').textContent=file.name;const ext=(file.name.split('.').pop()||'').toLowerCase();if(ext==='json')wb=workbookFromJson(JSON.parse(await file.text()));else if(ext==='csv'||ext==='tsv')wb=workbookFromCsv(await file.text(),{delimiter:ext==='tsv'?'\t':''});else wb=await readWorkbook(file);syncSheets();const after=sheetState();lastView=after;transactSheet('Ouvrir '+file.name,before,after);publishSheetContext('load-file');$('#status').textContent='Chargé · '+file.name+' · '+wb.SheetNames.length+' feuille(s) · moteur tabulaire partagé'}
$('#fileInput').onchange=e=>{const f=e.target.files?.[0];if(f)openFile(f).catch(err=>$('#status').textContent=err.message)};$('#openSheet').onclick=()=>$('#fileInput').click();$('#sheetSelect').onchange=()=>{render();queueSheetViewTxn('Changer de feuille')};$('#search').oninput=()=>{render();queueSheetViewTxn('Filtrer la feuille')};$('#delimiter').onchange=()=>queueSheetViewTxn('Modifier le séparateur CSV');$('#bom').onchange=()=>queueSheetViewTxn('Modifier BOM CSV');
$('#exportJson').onclick=()=>downloadJson(rowsToObjects(sheetRows()),bookName.replace(/\.[^.]+$/,'.json'));
$('#exportCsv').onclick=()=>{const sep=$('#delimiter').value==='\t'?'\t':$('#delimiter').value,csv=toCsv(sheetRows(),{delimiter:sep,bom:false});downloadCsv(csv,bookName.replace(/\.[^.]+$/,'.csv'),{bom:$('#bom').checked})};
$('#exportXlsx').onclick=()=>downloadBlob(workbookBlob(wb,'xlsx'),bookName.replace(/\.[^.]+$/,'.xlsx'));
$('#exportOds').onclick=()=>downloadBlob(workbookBlob(wb,'ods'),bookName.replace(/\.[^.]+$/,'.ods'));
document.addEventListener('studio-v2:action',e=>{const a=e.detail?.action,map={openSheet:'#openSheet',exportCsv:'#exportCsv',exportJson:'#exportJson',exportXlsx:'#exportXlsx',exportOds:'#exportOds'};const sel=map[a];if(sel)$(sel)?.click()});
const ws=XLSX.utils.aoa_to_sheet([['Colonne A','Colonne B'],['Exemple',123]]);XLSX.utils.book_append_sheet(wb,ws,'Feuille1');syncSheets();lastView=sheetState();publishSheetContext('ready');window.__NLAB_SPREADSHEET_STUDIO__={openFile,getWorkbook:()=>wb};
