import{downloadBlob,safeName,setStatus,toast}from'../../_shared/studio-v1/core.js';
function blobDataUrl(blob){return new Promise((res,rej)=>{const r=new FileReader();r.onload=()=>res(r.result);r.onerror=()=>rej(r.error);r.readAsDataURL(blob)})}
function similarity(a,b){a=String(a||'').replace(/\s+/g,' ').trim();b=String(b||'').replace(/\s+/g,' ').trim();if(!a&&!b)return 1;if(!a||!b)return 0;const sa=new Set(a.split(' ')),sb=new Set(b.split(' '));let common=0;for(const x of sa)if(sb.has(x))common++;return common/Math.max(sa.size,sb.size,1)}
async function textOfPdfjs(doc,page){const p=await doc.getPage(page),tc=await p.getTextContent();return tc.items.map(x=>x.str).join(' ')}
export class AdvancedPDFTools{
 constructor({engine,annotations,variables}){this.engine=engine;this.annotations=annotations;this.variables=variables}
 async pageImage(page,{type='png',scale=2,quality=.9}={}){const mime=type==='jpg'?'image/jpeg':'image/png',r=await this.engine.pageRaster(page,{scale,type:mime,quality});return r.blob}
 async downloadPageImage(page,opt={}){const type=opt.type||'png',blob=await this.pageImage(page,opt),name=safeName(this.engine.fileName.replace(/\.pdf$/i,''))+'_p'+String(page).padStart(3,'0')+'.'+type;downloadBlob(blob,name);return name}
 async allImagesZip({type='png',scale=2,quality=.9,pages}={}){if(!window.JSZip)throw new Error('JSZip indisponible');const zip=new JSZip(),list=pages?.length?pages:Array.from({length:this.engine.pageCount},(_,i)=>i+1),stem=safeName(this.engine.fileName.replace(/\.pdf$/i,''));for(let i=0;i<list.length;i++){setStatus('PDF → '+type.toUpperCase()+' '+(i+1)+' / '+list.length);const p=list[i],blob=await this.pageImage(p,{type,scale,quality});zip.file(stem+'_p'+String(p).padStart(3,'0')+'.'+type,blob)}return zip.generateAsync({type:'blob',compression:'DEFLATE'})}
 async headerFooter(pages,{header='',footer='',headerLeft='',headerRight='',footerLeft='',footerRight='',fontSize=9,qrTemplate='',qrPosition='none',qrSize=38,qrFactory=null}={}){
  const bytes=await this.engine.baseBytes(),doc=await PDFLib.PDFDocument.load(bytes,{ignoreEncryption:true}),font=await doc.embedFont(PDFLib.StandardFonts.Helvetica),targets=new Set(pages),total=doc.getPageCount(),color=PDFLib.rgb(.25,.3,.35);
  const draw=(page,text,slot,y,width)=>{if(!text)return;const w=Math.min(font.widthOfTextAtSize(text,fontSize),Math.max(20,width-64));let x=32;if(slot==='center')x=Math.max(32,(width-w)/2);if(slot==='right')x=Math.max(32,width-32-w);page.drawText(text,{x,y,size:fontSize,font,color,maxWidth:Math.max(20,width-64)})};
  const dataBytes=url=>{const m=String(url||'').match(/^data:image\/(png|jpeg|jpg);base64,(.+)$/i);if(!m)throw new Error('QR image invalide');const bin=atob(m[2]),u=new Uint8Array(bin.length);for(let i=0;i<bin.length;i++)u[i]=bin.charCodeAt(i);return{type:m[1].toLowerCase(),bytes:u}};
  for(let p=1;p<=total;p++){if(!targets.has(p))continue;this.variables.setRuntime({PAGE:p,PAGES:total});const page=doc.getPage(p-1),{width,height}=page.getSize(),ctx={PAGE:p,PAGES:total};
   const hl=this.variables.resolve(headerLeft,this.engine.fileName,ctx),hc=this.variables.resolve(header,this.engine.fileName,ctx),hr=this.variables.resolve(headerRight,this.engine.fileName,ctx),fl=this.variables.resolve(footerLeft,this.engine.fileName,ctx),fc=this.variables.resolve(footer,this.engine.fileName,ctx),fr=this.variables.resolve(footerRight,this.engine.fileName,ctx);
   draw(page,hl,'left',height-22,width);draw(page,hc,'center',height-22,width);draw(page,hr,'right',height-22,width);draw(page,fl,'left',14,width);draw(page,fc,'center',14,width);draw(page,fr,'right',14,width);
   if(qrPosition!=='none'&&qrTemplate&&qrFactory){const value=this.variables.resolve(qrTemplate,this.engine.fileName,ctx);if(value){const data=dataBytes(await qrFactory(value)),img=data.type==='png'?await doc.embedPng(data.bytes):await doc.embedJpg(data.bytes),s=Math.max(18,Math.min(90,Number(qrSize)||38)),top=qrPosition.startsWith('header'),right=qrPosition.endsWith('right'),x=right?width-28-s:28,y=top?height-30-s:28;page.drawImage(img,{x,y,width:s,height:s})}}
  }
  this.variables.setRuntime({PAGE:this.engine.currentPage,PAGES:this.engine.pageCount});await this.engine.setBytes(new Uint8Array(await doc.save()));this.variables.setOperation({annot:true});return pages
 }
 async cropPages(pages,{left=0,right=0,top=0,bottom=0}={}){const targets=new Set(pages);for(let p=1;p<=this.engine.pageCount;p++){if(!targets.has(p))continue;const page=this.engine.pdfDoc.getPage(p-1),{width,height}=page.getSize(),x=width*left/100,y=height*bottom/100,w=width*(1-(left+right)/100),h=height*(1-(top+bottom)/100);if(w<40||h<40)throw new Error('Recadrage trop important');page.setCropBox(x,y,w,h)}await this.engine.setBytes(new Uint8Array(await this.engine.pdfDoc.save()));return pages}
 inspectForms(){const form=this.engine.pdfDoc?.getForm?.();if(!form)return[];return form.getFields().map(f=>({name:f.getName(),type:f.constructor.name,value:typeof f.getText==='function'?f.getText():typeof f.isChecked==='function'?f.isChecked():''}))}
 async addTextField(page,name,{xPct=20,yPct=20,wPct=45,h=26}={}){const form=this.engine.pdfDoc.getForm(),field=form.createTextField(name),pg=this.engine.pdfDoc.getPage(page-1),{width,height}=pg.getSize();field.addToPage(pg,{x:width*xPct/100,y:height*(1-yPct/100)-h,width:width*wPct/100,height:h,borderWidth:1,borderColor:PDFLib.rgb(.25,.45,.62),backgroundColor:PDFLib.rgb(.98,.99,1),textColor:PDFLib.rgb(.08,.12,.16)});await this.engine.setBytes(new Uint8Array(await this.engine.pdfDoc.save()));return name}
 async fillForms(values={}){const form=this.engine.pdfDoc.getForm();for(const f of form.getFields()){const n=f.getName();if(!(n in values))continue;try{if(typeof f.setText==='function')f.setText(String(values[n]??''));else if(typeof f.check==='function'&&values[n])f.check();else if(typeof f.uncheck==='function'&&!values[n])f.uncheck();else if(typeof f.select==='function')f.select(String(values[n]))}catch{}}await this.engine.setBytes(new Uint8Array(await this.engine.pdfDoc.save()))}
 async flattenForms(){const form=this.engine.pdfDoc.getForm();form.flatten();await this.engine.setBytes(new Uint8Array(await this.engine.pdfDoc.save()))}
 async applySecureRedactions(pages,{dpi=150}={}){const targets=new Set(pages),out=await PDFLib.PDFDocument.create();for(let p=1;p<=this.engine.pageCount;p++){const redactions=this.engine.annotations(p).filter(a=>a.type==='redaction');if(!targets.has(p)||!redactions.length){const[cp]=await out.copyPages(this.engine.pdfDoc,[p-1]);out.addPage(cp);continue}setStatus('Caviardage page '+p);const pdfPage=await this.engine.pdfjs.getPage(p),vp=pdfPage.getViewport({scale:Math.max(1,dpi/72)}),c=document.createElement('canvas');c.width=Math.ceil(vp.width);c.height=Math.ceil(vp.height);const ctx=c.getContext('2d');await pdfPage.render({canvasContext:ctx,viewport:vp}).promise;for(const a of redactions){ctx.fillStyle='#000';ctx.fillRect((a.xPct||0)/100*c.width,(a.yPct||0)/100*c.height,(a.wPct||20)/100*c.width,(a.hPct||5)/100*c.height)}const blob=await new Promise(r=>c.toBlob(r,'image/jpeg',.92)),img=await out.embedJpg(await blob.arrayBuffer()),src=this.engine.pdfDoc.getPage(p-1),sz=src.getSize(),np=out.addPage([sz.width,sz.height]);np.drawImage(img,{x:0,y:0,width:sz.width,height:sz.height});this.engine.pageAnnotations.set(p,this.engine.annotations(p).filter(a=>a.type!=='redaction'))}await this.engine.setBytes(new Uint8Array(await out.save()));return pages}
 async compare(file){const otherBytes=new Uint8Array(await file.arrayBuffer()),other=await pdfjsLib.getDocument({data:otherBytes.slice()}).promise,n=Math.max(this.engine.pageCount,other.numPages),rows=[];for(let p=1;p<=n;p++){const a=p<=this.engine.pageCount?await this.engine.pageText(p):'',b=p<=other.numPages?await textOfPdfjs(other,p):'',score=similarity(a,b);rows.push({page:p,similarity:score,same:score>.995,status:score>.995?'identique':score>.8?'proche':'différent'})}return{left:{name:this.engine.fileName,pages:this.engine.pageCount},right:{name:file.name,pages:other.numPages},rows,average:rows.reduce((s,x)=>s+x.similarity,0)/Math.max(1,rows.length)}}
 async cleanMetadata(){const d=this.engine.pdfDoc;d.setTitle('');d.setAuthor('');d.setSubject('');d.setKeywords([]);d.setCreator('nLab PDF Studio 1.0');d.setProducer('nLab PDF Studio 1.0');await this.engine.setBytes(new Uint8Array(await d.save()));return true}
 signatureStructure(){if(!this.engine.bytes)return{hasSignature:false};const s=new TextDecoder('latin1').decode(this.engine.bytes),byteRanges=[...s.matchAll(/\/ByteRange\s*\[([^\]]+)\]/g)].map(m=>m[1].trim()),sigCount=(s.match(/\/Type\s*\/Sig\b/g)||[]).length;return{hasSignature:byteRanges.length>0||sigCount>0,byteRanges,sigCount,note:'Inspection structurelle uniquement — aucune validation cryptographique.'}}
 async batchCleanMetadata(files){if(!window.JSZip)throw new Error('JSZip indisponible');const zip=new JSZip();for(const file of files){if(!/\.pdf$/i.test(file.name))continue;const d=await PDFLib.PDFDocument.load(await file.arrayBuffer(),{ignoreEncryption:true});d.setTitle('');d.setAuthor('');d.setSubject('');d.setKeywords([]);d.setCreator('nLab PDF Studio 1.0');d.setProducer('nLab PDF Studio 1.0');zip.file(safeName(file.name),new Uint8Array(await d.save()))}return zip.generateAsync({type:'blob',compression:'DEFLATE'})}
}
