import{uid,qs,qsa,clamp,toast}from'../../_shared/studio-v1/core.js';
import{hexToRgb}from'../../_shared/studio-v2/color-control.js';
import{rotateObject,toggleObjectLock}from'../../_shared/studio-v2/object-transform-service.js';
function hexRgb(hex='#316D9A'){const c=hexToRgb(hex)||{r:49,g:109,b:154};return{r:c.r/255,g:c.g/255,b:c.b/255}}
function dataUrlBytes(dataUrl){const [head,b64]=dataUrl.split(','),bin=atob(b64),u=new Uint8Array(bin.length);for(let i=0;i<bin.length;i++)u[i]=bin.charCodeAt(i);return{bytes:u,type:head.includes('png')?'png':'jpg'}}
export class AnnotationManager{
 constructor({engine,layer,canvasWrap,variables}){this.engine=engine;this.layer=layer;this.canvasWrap=canvasWrap;this.variables=variables;this.tool='select';this.layer.style.pointerEvents='none';this.selectedId=null;this.imageData=null;this.signatureData=null;this.penDraft=null;this.bindSurface();engine.addEventListener('annotations',()=>this.render());engine.addEventListener('page',()=>this.render());}
 setTool(t){this.tool=t;this.layer.style.pointerEvents=t==='select'?'none':'auto';qsa('.toolBtn').forEach(b=>b.classList.toggle('active',b.dataset.tool===t));}
 setImageData(data){this.imageData=data}setSignatureData(data){this.signatureData=data}
 currentStyle(){return{fontSize:Number(qs('#annotationSize')?.value||12),color:qs('#annotationColor')?.value||'#316D9A'}}
 pointPct(ev){const r=this.canvasWrap.getBoundingClientRect();return{x:clamp((ev.clientX-r.left)/r.width*100,0,99),y:clamp((ev.clientY-r.top)/r.height*100,0,99)}}
 bindSurface(){this.layer.addEventListener('pointerdown',e=>{if(this.tool==='select')return;if(e.target.closest?.('.deleteAnn'))return;const p=this.pointPct(e);if(this.tool==='text'){this.addText(this.engine.currentPage,p.x,p.y,qs('#annotationText')?.value||'Texte');this.setTool('select')}else if(this.tool==='highlight'){this.addHighlight(this.engine.currentPage,p.x,p.y);this.setTool('select')}else if(this.tool==='image'){if(!this.imageData)return qs('#imageInput')?.click();this.addImage(this.engine.currentPage,p.x,p.y,this.imageData,'image');this.setTool('select')}else if(this.tool==='signature'){if(!this.signatureData)return toast('Chargez ou dessinez une signature');this.addImage(this.engine.currentPage,p.x,p.y,this.signatureData,'signature');this.setTool('select')}else if(this.tool==='redaction'){this.addRedaction(this.engine.currentPage,p.x,p.y);this.setTool('select')}else if(this.tool==='pen'){this.penDraft={page:this.engine.currentPage,points:[p],color:this.currentStyle().color,width:2};this.layer.setPointerCapture?.(e.pointerId)}});
 this.layer.addEventListener('pointermove',e=>{if(this.tool==='pen'&&this.penDraft){this.penDraft.points.push(this.pointPct(e));this.render()}});
 this.layer.addEventListener('pointerup',e=>{if(this.tool==='pen'&&this.penDraft){if(this.penDraft.points.length>1)this.engine.addAnnotation(this.penDraft.page,{id:uid('pen'),type:'pen',points:this.penDraft.points,color:this.penDraft.color,width:this.penDraft.width});this.penDraft=null;this.render()}});
 }
 addText(page,x,y,text){const s=this.currentStyle();return this.engine.addAnnotation(page,{type:'text',xPct:x,yPct:y,text,fontSize:s.fontSize,color:s.color,rotation:0,opacity:1,locked:false,wPct:24})}
 addHighlight(page,x,y){return this.engine.addAnnotation(page,{type:'highlight',xPct:x,yPct:y,wPct:22,hPct:4,color:'#FFEB3B',opacity:.35,rotation:0,locked:false})}
 addStamp(page,xPct,yPct,template){const text=this.variables.resolve(template,this.engine.fileName),s=this.currentStyle();this.variables.setOperation({stamp:true,annot:true});return this.engine.addAnnotation(page,{type:'stamp',xPct,yPct,text,fontSize:s.fontSize,color:'#A1453F',rotation:0,opacity:1,locked:false,wPct:28})}
 addStampScope(pages,xPct,yPct,template){for(const p of pages)this.addStamp(p,xPct,yPct,template)}
 addRedaction(page,x,y){return this.engine.addAnnotation(page,{type:'redaction',xPct:x,yPct:y,wPct:24,hPct:6,color:'#000000',opacity:1,rotation:0,locked:false})}
 addImage(page,x,y,dataUrl,kind='image'){this.variables.setOperation({annot:true});return this.engine.addAnnotation(page,{type:kind,xPct:x,yPct:y,wPct:20,dataUrl,rotation:0,opacity:1,locked:false})}
 selected(){return this.engine.annotations(this.engine.currentPage).find(a=>a.id===this.selectedId)||null}
 select(id){this.selectedId=id;this.render();this.layer.dispatchEvent(new CustomEvent('objectselected',{detail:{object:this.selected()}}));return this.selected()}
 updateSelected(patch={}){const a=this.selected();if(!a)return null;Object.assign(a,patch);this.engine.dispatchEvent(new Event('annotations'));this.layer.dispatchEvent(new CustomEvent('objectselected',{detail:{object:a}}));return a}
 rotateSelected(delta){const a=rotateObject(this.selected(),delta);if(!a)return null;this.engine.dispatchEvent(new Event('annotations'));return a}
 toggleLock(){const a=toggleObjectLock(this.selected());if(!a)return null;this.engine.dispatchEvent(new Event('annotations'));return a}
 moveLayer(delta){const arr=this.engine.annotations(this.engine.currentPage),i=arr.findIndex(a=>a.id===this.selectedId);if(i<0)return;const j=clamp(i+delta,0,arr.length-1);if(i===j)return;const [a]=arr.splice(i,1);arr.splice(j,0,a);this.engine.dispatchEvent(new Event('annotations'))}
 render(){const page=this.engine.currentPage,anns=this.engine.annotations(page),rect=this.canvasWrap.getBoundingClientRect();this.layer.style.width=rect.width+'px';this.layer.style.height=rect.height+'px';this.layer.innerHTML='';const all=[...anns];if(this.penDraft?.page===page)all.push({...this.penDraft,id:'__draft'});for(const a of all){if(a.type==='pen'){const svg=document.createElementNS('http://www.w3.org/2000/svg','svg');svg.classList.add('annotation');svg.style.left='0';svg.style.top='0';svg.style.width='100%';svg.style.height='100%';svg.style.border='0';svg.style.background='transparent';svg.style.pointerEvents=a.id==='__draft'?'none':'auto';const pl=document.createElementNS(svg.namespaceURI,'polyline');pl.setAttribute('fill','none');pl.setAttribute('stroke',a.color||'#316D9A');pl.setAttribute('stroke-width',String(a.width||2));pl.setAttribute('points',a.points.map(p=>(p.x/100*rect.width)+','+(p.y/100*rect.height)).join(' '));svg.append(pl);if(a.id!=='__draft'){svg.dataset.id=a.id;svg.onclick=e=>{e.stopPropagation();this.selectedId=a.id;this.render();this.layer.dispatchEvent(new CustomEvent('objectselected',{detail:{object:a}}))};if(a.id===this.selectedId)svg.classList.add('selected')}this.layer.append(svg);continue}
 const el=document.createElement('div');el.className='annotation '+a.type+(a.id===this.selectedId?' selected':'');el.dataset.id=a.id;el.style.left=(a.xPct||0)+'%';el.style.top=(a.yPct||0)+'%';el.style.color=a.color||'#316D9A';el.style.opacity=String(a.opacity??1);el.style.transform='rotate('+(Number(a.rotation)||0)+'deg)';el.style.transformOrigin='top left';if(a.locked)el.classList.add('lockedObject');if(a.fontSize)el.style.fontSize=a.fontSize+'px';if(a.type==='highlight'){el.style.width=(a.wPct||20)+'%';el.style.height=Math.max(16,(a.hPct||4)/100*rect.height)+'px';el.style.background=(a.color||'#FFEB3B')+'88';el.textContent=''}else if(a.type==='redaction'){el.style.width=(a.wPct||24)+'%';el.style.height=Math.max(20,(a.hPct||6)/100*rect.height)+'px';el.style.background='#000';el.textContent=''}else if(a.type==='image'||a.type==='signature'){el.style.width=(a.wPct||20)+'%';el.innerHTML='<img src="'+a.dataUrl+'" alt="'+a.type+'">'}else{el.textContent=a.text||'';if(a.wPct)el.style.width=(a.wPct||24)+'%'}
 if(a.id===this.selectedId){const bar=document.createElement('div');bar.className='objectControlBar';bar.innerHTML='<button type="button" data-act="lock" title="Verrouiller / déverrouiller">'+(a.locked?'🔒':'🔓')+'</button><button type="button" data-act="rotl" title="Rotation -90°">↺</button><button type="button" data-act="rotr" title="Rotation +90°">↻</button><button type="button" data-act="del" title="Supprimer">×</button>';bar.querySelector('[data-act="lock"]').onclick=e=>{e.stopPropagation();this.toggleLock()};bar.querySelector('[data-act="rotl"]').onclick=e=>{e.stopPropagation();this.rotateSelected(-90)};bar.querySelector('[data-act="rotr"]').onclick=e=>{e.stopPropagation();this.rotateSelected(90)};bar.querySelector('[data-act="del"]').onclick=e=>{e.stopPropagation();this.engine.removeAnnotation(a.id);this.selectedId=null;this.layer.dispatchEvent(new CustomEvent('objectselected',{detail:{object:null}}))};el.append(bar);if(!a.locked&&['highlight','redaction','image','signature','stamp','text'].includes(a.type)){const h=document.createElement('span');h.className='resizeHandle';h.title='Redimensionner';h.onpointerdown=e=>{e.stopPropagation();const start=this.pointPct(e),sw=a.wPct||20,sh=a.hPct||0;h.setPointerCapture?.(e.pointerId);const mv=ev=>{const p=this.pointPct(ev);a.wPct=clamp(sw+(p.x-start.x),3,95);if(a.type==='highlight'||a.type==='redaction')a.hPct=clamp((sh||5)+(p.y-start.y),1,60);this.render()};const up=()=>{h.removeEventListener('pointermove',mv);h.removeEventListener('pointerup',up);this.engine.dispatchEvent(new Event('annotations'))};h.addEventListener('pointermove',mv);h.addEventListener('pointerup',up)};el.append(h)}}
 el.onpointerdown=e=>{if(e.target.closest('button')||e.target.closest('.resizeHandle'))return;if(this.tool!=='select')return;e.stopPropagation();this.selectedId=a.id;this.layer.dispatchEvent(new CustomEvent('objectselected',{detail:{object:a}}));if(a.locked){this.render();return}const start=this.pointPct(e),sx=a.xPct||0,sy=a.yPct||0;el.setPointerCapture?.(e.pointerId);const mv=ev=>{const p=this.pointPct(ev);a.xPct=clamp(sx+p.x-start.x,0,98);a.yPct=clamp(sy+p.y-start.y,0,98);el.style.left=a.xPct+'%';el.style.top=a.yPct+'%'};const up=()=>{el.removeEventListener('pointermove',mv);el.removeEventListener('pointerup',up);this.engine.dispatchEvent(new Event('annotations'))};el.addEventListener('pointermove',mv);el.addEventListener('pointerup',up);this.render()};this.layer.append(el)}}
 deleteSelected(){if(!this.selectedId)return toast('Aucun objet sélectionné');this.engine.removeAnnotation(this.selectedId);this.selectedId=null}
 async exportBytes(){const doc=await PDFLib.PDFDocument.load(await this.engine.baseBytes(),{ignoreEncryption:true}),font=await doc.embedFont(PDFLib.StandardFonts.Helvetica);for(let p=1;p<=doc.getPageCount();p++){const page=doc.getPage(p-1),{width,height}=page.getSize();for(const a of this.engine.annotations(p)){const c=hexRgb(a.color),color=PDFLib.rgb(c.r,c.g,c.b),x=(a.xPct||0)/100*width,yTop=(a.yPct||0)/100*height;if(a.type==='text'||a.type==='stamp'){const size=a.fontSize||12,y=height-yTop-size;page.drawText(String(a.text||''),{x,y,size,font,color,maxWidth:Math.max(40,width-x-16),lineHeight:size*1.2,rotate:PDFLib.degrees(Number(a.rotation)||0),opacity:a.opacity??1})}else if(a.type==='highlight'){page.drawRectangle({x,y:height-yTop-(a.hPct||4)/100*height,width:(a.wPct||20)/100*width,height:(a.hPct||4)/100*height,color,opacity:a.opacity??.35,rotate:PDFLib.degrees(Number(a.rotation)||0)})}else if(a.type==='redaction'){page.drawRectangle({x,y:height-yTop-(a.hPct||6)/100*height,width:(a.wPct||24)/100*width,height:(a.hPct||6)/100*height,color:PDFLib.rgb(0,0,0),opacity:a.opacity??1,rotate:PDFLib.degrees(Number(a.rotation)||0)})}else if(a.type==='image'||a.type==='signature'){const d=dataUrlBytes(a.dataUrl),img=d.type==='png'?await doc.embedPng(d.bytes):await doc.embedJpg(d.bytes),w=(a.wPct||20)/100*width,h=w*(img.height/img.width);page.drawImage(img,{x,y:height-yTop-h,width:w,height:h,rotate:PDFLib.degrees(Number(a.rotation)||0),opacity:a.opacity??1})}else if(a.type==='pen'&&a.points?.length>1){for(let i=1;i<a.points.length;i++){const A=a.points[i-1],B=a.points[i];page.drawLine({start:{x:A.x/100*width,y:height-A.y/100*height},end:{x:B.x/100*width,y:height-B.y/100*height},thickness:a.width||2,color})}}}}return new Uint8Array(await doc.save())}
}