import{uid,setStatus,fileStem}from'../../_shared/studio-v1/core.js';
const {PDFDocument,degrees}=PDFLib;
async function blobToDataURL(blob){return new Promise((res,rej)=>{const r=new FileReader();r.onload=()=>res(r.result);r.onerror=()=>rej(r.error);r.readAsDataURL(blob)})}
async function imageFileToPdf(file){const data=await file.arrayBuffer(),doc=await PDFDocument.create();let img;if(/png/i.test(file.type)||/\.png$/i.test(file.name))img=await doc.embedPng(data);else img=await doc.embedJpg(data);const w=img.width,h=img.height,maxW=595,maxH=842,ratio=Math.min(maxW/w,maxH/h,1),pw=w*ratio,ph=h*ratio,p=doc.addPage([pw,ph]);p.drawImage(img,{x:0,y:0,width:pw,height:ph});return new Uint8Array(await doc.save())}
async function docxFileToPdf(file){if(!window.mammoth)throw new Error('Mammoth DOCX non chargé');const r=await mammoth.extractRawText({arrayBuffer:await file.arrayBuffer()}),doc=await PDFDocument.create(),font=await doc.embedFont(PDFLib.StandardFonts.Helvetica);let page=doc.addPage([595,842]),y=800;for(const para of String(r.value||'').split(/\n+/)){for(const line of wrap(para,88)){if(y<45){page=doc.addPage([595,842]);y=800}page.drawText(line,{x:42,y,size:10,font,color:PDFLib.rgb(.08,.12,.16)});y-=14}y-=5}return new Uint8Array(await doc.save())}
function wrap(s,n){const words=String(s||'').split(/\s+/),out=[],a=[];let len=0;for(const w of words){if(len+w.length+1>n&&a.length){out.push(a.join(' '));a.length=0;len=0}a.push(w);len+=w.length+1}if(a.length)out.push(a.join(' '));return out.length?out:['']}
export class PDFEngine extends EventTarget{
 constructor(){super();this.bytes=null;this.pdfDoc=null;this.pdfjs=null;this.fileName='document.pdf';this.currentPage=1;this.selected=new Set();this.pageAnnotations=new Map();this.sourceFile=null;this.dirty=false}
 get pageCount(){return this.pdfDoc?.getPageCount?.()||0}
 async loadFile(file){this.sourceFile=file;this.fileName=file.name||'document.pdf';let bytes;if(/\.pdf$/i.test(file.name)||file.type==='application/pdf')bytes=new Uint8Array(await file.arrayBuffer());else if(/^image\//.test(file.type)||/\.(png|jpe?g|webp)$/i.test(file.name))bytes=await imageFileToPdf(file);else if(/\.docx$/i.test(file.name))bytes=await docxFileToPdf(file);else throw new Error('Format non pris en charge par PDF Studio : '+file.name);await this.setBytes(bytes,{resetAnnotations:true});setStatus(this.fileName+' · '+this.pageCount+' page(s)');return this}
 async setBytes(bytes,{resetAnnotations=false}={}){this.bytes=bytes instanceof Uint8Array?bytes:new Uint8Array(bytes);this.pdfDoc=await PDFDocument.load(this.bytes,{ignoreEncryption:true});this.pdfjs=await pdfjsLib.getDocument({data:this.bytes.slice()}).promise;this.currentPage=Math.min(Math.max(1,this.currentPage),this.pageCount||1);this.selected=new Set([...this.selected].filter(p=>p<=this.pageCount));if(resetAnnotations)this.pageAnnotations.clear();this.dirty=true;this.dispatchEvent(new Event('change'))}
 targetPages(scope='current'){if(!this.pageCount)return[];if(scope==='all')return Array.from({length:this.pageCount},(_,i)=>i+1);if(scope==='selected')return [...this.selected].filter(p=>p>=1&&p<=this.pageCount).sort((a,b)=>a-b);return[this.currentPage]}
 selectPage(page){this.currentPage=Math.max(1,Math.min(this.pageCount,page));this.dispatchEvent(new CustomEvent('page',{detail:{page:this.currentPage}}))}
 toggleSelected(page,v){if(v)this.selected.add(page);else this.selected.delete(page);this.dispatchEvent(new Event('selection'))}
 selectAll(){this.selected=new Set(Array.from({length:this.pageCount},(_,i)=>i+1));this.dispatchEvent(new Event('selection'))}
 selectNone(){this.selected.clear();this.dispatchEvent(new Event('selection'))}
 async renderPage(canvas,page=this.currentPage,zoom=1){if(!this.pdfjs)return;const p=await this.pdfjs.getPage(page),vp=p.getViewport({scale:zoom});canvas.width=Math.ceil(vp.width);canvas.height=Math.ceil(vp.height);canvas.style.width=canvas.width+'px';canvas.style.height=canvas.height+'px';await p.render({canvasContext:canvas.getContext('2d'),viewport:vp}).promise;return vp}
 async renderThumb(canvas,page,zoom=.2){if(!this.pdfjs)return;const p=await this.pdfjs.getPage(page),vp=p.getViewport({scale:zoom});canvas.width=Math.ceil(vp.width);canvas.height=Math.ceil(vp.height);await p.render({canvasContext:canvas.getContext('2d'),viewport:vp}).promise;return vp}
 async rotate(pages,delta){if(!pages.length)return;for(const n of pages){const p=this.pdfDoc.getPage(n-1),a=p.getRotation()?.angle||0;p.setRotation(degrees((a+delta+360)%360))}await this.setBytes(new Uint8Array(await this.pdfDoc.save()));return pages}
 async addBlank(after=this.currentPage){const ref=this.pdfDoc.getPage(Math.max(0,after-1)),{width,height}=ref.getSize();this.pdfDoc.insertPage(after,[width,height]);this.shiftAnnotations(after+1,1);this.currentPage=after+1;await this.setBytes(new Uint8Array(await this.pdfDoc.save()));return this.currentPage}
 async duplicate(page=this.currentPage){const out=await PDFDocument.create();for(let i=0;i<this.pageCount;i++){const [cp]=await out.copyPages(this.pdfDoc,[i]);out.addPage(cp);if(i===page-1){const [dup]=await out.copyPages(this.pdfDoc,[i]);out.addPage(dup)}}this.shiftAnnotations(page+1,1);const originals=this.pageAnnotations.get(page)||[];if(originals.length)this.pageAnnotations.set(page+1,structuredClone(originals));this.currentPage=page+1;await this.setBytes(new Uint8Array(await out.save()))}
 async deletePages(pages){const set=new Set(pages);if(!set.size)return;if(set.size>=this.pageCount)throw new Error('Impossible de supprimer toutes les pages');const out=await PDFDocument.create(),map=new Map();let newIndex=0;for(let i=1;i<=this.pageCount;i++){if(set.has(i))continue;const [cp]=await out.copyPages(this.pdfDoc,[i-1]);out.addPage(cp);newIndex++;if(this.pageAnnotations.has(i))map.set(newIndex,this.pageAnnotations.get(i))}this.pageAnnotations=map;this.selected.clear();this.currentPage=Math.min(this.currentPage,out.getPageCount());await this.setBytes(new Uint8Array(await out.save()))}
 async extractPages(pages){if(!pages.length)throw new Error('Aucune page à extraire');const out=await PDFDocument.create(),copies=await out.copyPages(this.pdfDoc,pages.map(x=>x-1));copies.forEach(p=>out.addPage(p));return new Uint8Array(await out.save())}
 async mergeFiles(files){const out=await PDFDocument.create();for(const f of files){if(!/\.pdf$/i.test(f.name))continue;const d=await PDFDocument.load(await f.arrayBuffer(),{ignoreEncryption:true}),copies=await out.copyPages(d,d.getPageIndices());copies.forEach(p=>out.addPage(p))}if(!out.getPageCount())throw new Error('Aucun PDF à fusionner');this.fileName='fusion.pdf';this.pageAnnotations.clear();await this.setBytes(new Uint8Array(await out.save()),{resetAnnotations:true})}
 addAnnotation(page,ann){const arr=this.pageAnnotations.get(page)||[];ann={id:ann.id||uid('ann'),...ann};arr.push(ann);this.pageAnnotations.set(page,arr);this.dirty=true;this.dispatchEvent(new Event('annotations'));return ann}
 removeAnnotation(id){for(const [p,a] of this.pageAnnotations){const n=a.filter(x=>x.id!==id);if(n.length!==a.length){this.pageAnnotations.set(p,n);this.dispatchEvent(new Event('annotations'));return true}}return false}
 annotations(page=this.currentPage){return this.pageAnnotations.get(page)||[]}
 shiftAnnotations(from,delta){const entries=[...this.pageAnnotations.entries()].sort((a,b)=>delta>0?b[0]-a[0]:a[0]-b[0]);for(const [p,a] of entries)if(p>=from){this.pageAnnotations.delete(p);this.pageAnnotations.set(p+delta,a)}}
 async baseBytes(){return new Uint8Array(await this.pdfDoc.save())}
 async pageText(page){if(!this.pdfjs)return'';const p=await this.pdfjs.getPage(page),tc=await p.getTextContent();return tc.items.map(x=>x.str).join(' ')}
 async pageRaster(page,{scale=2,type='image/jpeg',quality=.85,gray=false}={}){const p=await this.pdfjs.getPage(page),vp=p.getViewport({scale}),c=document.createElement('canvas');c.width=Math.ceil(vp.width);c.height=Math.ceil(vp.height);const ctx=c.getContext('2d');await p.render({canvasContext:ctx,viewport:vp}).promise;if(gray){const im=ctx.getImageData(0,0,c.width,c.height);for(let i=0;i<im.data.length;i+=4){const y=.299*im.data[i]+.587*im.data[i+1]+.114*im.data[i+2];im.data[i]=im.data[i+1]=im.data[i+2]=y}ctx.putImageData(im,0,0)}const blob=await new Promise(r=>c.toBlob(r,type,quality));return{blob,width:c.width,height:c.height,dataUrl:await blobToDataURL(blob)}}
}
export{fileStem};