import{setStatus,toast}from'../../_shared/studio-v1/core.js';
import{runOcr}from'../../_shared/studio-v2/ocr-service.js';
function wrapText(text,font,size,maxWidth){const words=String(text||'').split(/\s+/),lines=[],a=[];for(const w of words){const t=[...a,w].join(' ');if(a.length&&font.widthOfTextAtSize(t,size)>maxWidth){lines.push(a.join(' '));a.length=0}a.push(w)}if(a.length)lines.push(a.join(' '));return lines}
async function translateBrowser(text,source,target){if(!window.Translator?.create)throw new Error('Browser Translator API indisponible');if(window.Translator.availability){const av=await Translator.availability({sourceLanguage:source,targetLanguage:target});if(av==='unavailable')throw new Error('Paire de langues indisponible')}const tr=await Translator.create({sourceLanguage:source,targetLanguage:target});return tr.translate(text)}
async function translateEndpoint(endpoint,text,source,target){const r=await fetch(endpoint,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({text,source,target})});if(!r.ok)throw new Error('Endpoint traduction HTTP '+r.status);const d=await r.json();const out=d.translation??d.translatedText??d.text??d.result;if(typeof out!=='string')throw new Error('Réponse traduction invalide');return out}
export class PDFTools{
 constructor({engine,annotations,variables}){this.engine=engine;this.annotations=annotations;this.variables=variables}
 async ocr(pages,{lang='fra',dpi=150,onProgress}={}){const out=[];for(let i=0;i<pages.length;i++){const p=pages[i];setStatus('OCR page '+p+' / '+pages.length);const r=await this.engine.pageRaster(p,{scale:Math.max(1,dpi/72),type:'image/png'});const res=await runOcr(r.blob,{engine:'auto',language:lang,logger:m=>onProgress?.({page:p,...m})});out.push('--- Page '+p+' ---\n'+String(res.text||'').trim())}this.variables.setOperation({ocr:true,dpi});setStatus('OCR terminé · '+pages.length+' page(s)');return out.join('\n\n')}
 async optimize(pages,{dpi=150,jpeg=82,gray=false}={}){const targets=new Set(pages),src=this.engine.pdfDoc,out=await PDFLib.PDFDocument.create();for(let p=1;p<=this.engine.pageCount;p++){setStatus('Optimisation page '+p+' / '+this.engine.pageCount);if(!targets.has(p)){const[cp]=await out.copyPages(src,[p-1]);out.addPage(cp);continue}const original=src.getPage(p-1),sz=original.getSize(),r=await this.engine.pageRaster(p,{scale:Math.max(1,dpi/72),type:'image/jpeg',quality:jpeg/100,gray}),img=await out.embedJpg(await r.blob.arrayBuffer()),np=out.addPage([sz.width,sz.height]);np.drawImage(img,{x:0,y:0,width:sz.width,height:sz.height})}const bytes=new Uint8Array(await out.save());this.variables.setOperation({dpi,jpeg,gray});await this.engine.setBytes(bytes);toast('Optimisation terminée');return bytes}
 async translateText(text,{source='fr',target='en',endpoint=''}={}){if(source===target)return text;let last;if(endpoint)try{return await translateEndpoint(endpoint,text,source,target)}catch(e){last=e}try{return await translateBrowser(text,source,target)}catch(e){last=e}throw new Error('Aucun moteur de traduction disponible'+(last?': '+last.message:''))}
 async bilingual({source='fr',target='en',layout='side-by-side',endpoint='',pages}={}){const srcBytes=await this.annotations.exportBytes(),srcDoc=await PDFLib.PDFDocument.load(srcBytes,{ignoreEncryption:true}),out=await PDFLib.PDFDocument.create(),font=await out.embedFont(PDFLib.StandardFonts.Helvetica);const list=pages?.length?pages:Array.from({length:this.engine.pageCount},(_,i)=>i+1);for(let i=0;i<list.length;i++){const p=list[i];setStatus('Traduction page '+p+' / '+list.length);const raw=await this.engine.pageText(p),translated=await this.translateText(raw,{source,target,endpoint}),srcPage=srcDoc.getPage(p-1),{width:w,height:h}=srcPage.getSize();if(layout==='facing'){const[copy]=await out.copyPages(srcDoc,[p-1]);out.addPage(copy);const tp=out.addPage([w,h]);drawTranslation(tp,translated,font,{x:42,y:h-48,width:w-84,height:h-90})}else{let left=.5;if(layout==='side-13')left=1/3;if(layout==='side-23')left=2/3;const page=out.addPage([w*2,h]),embedded=await out.embedPage(srcPage);page.drawPage(embedded,{x:0,y:0,width:w*2*left,height:h});page.drawLine({start:{x:w*2*left,y:0},end:{x:w*2*left,y:h},thickness:1,color:PDFLib.rgb(.75,.78,.8)});drawTranslation(page,translated,font,{x:w*2*left+28,y:h-42,width:w*2*(1-left)-56,height:h-80})}}
 setStatus('PDF bilingue prêt');return new Uint8Array(await out.save())}
}
function drawTranslation(page,text,font,{x,y,width,height}){const size=9,line=size*1.35,lines=wrapText(text,font,size,width);let yy=y;page.drawText('TRADUCTION',{x,y:yy,size:10,font,color:PDFLib.rgb(.19,.43,.6)});yy-=18;for(const l of lines){if(yy<y-height+20)break;page.drawText(l,{x,y:yy,size,font,color:PDFLib.rgb(.08,.12,.16)});yy-=line}}
