import{qs,qsa,toast,setStatus,bindSidebar,bindSectionControls,wireMenuTabs,jsonDownload,readJsonFile,today,downloadBlob,safeName}from'../../_shared/studio-v1/core.js';
import{VariableEngine}from'../../_shared/studio-v1/variables.js';
import{FileWorkspace}from'../../_shared/studio-v1/file-io.js';
import{DriveService}from'../../_shared/studio-v1/drive.js';
import{PDFEngine}from'./pdf-engine.js';
import{AnnotationManager}from'./annotations.js';
import{PDFTools}from'./pdf-tools.js';
import{icon}from'../../_shared/studio-v1/icons.js';

const VERSION='1.0.0 TEST',vars=new VariableEngine(),engine=new PDFEngine(),drive=new DriveService({storageKey:'nlab-pdf-studio-v1-google'});
const history=[],stamps=[
{id:'valid',label:'VALIDÉ',template:'VALIDÉ · {INITIALS} · {STAMP_DATE:DD/MM/YYYY}'},
{id:'date',label:'DATE',template:'{STAMP_DATE:DD/MM/YYYY}'},
{id:'received',label:'REÇU',template:'REÇU le {DATE_A:DD/MM/YYYY} · {INITIALS}'},
{id:'nc',label:'NON CONFORME',template:'NON CONFORME · {DATE_B:DD/MM/YYYY} · {INITIALS}'},
{id:'display',label:'AFFICHÉ JUSQU’AU',template:'AFFICHÉ · jusqu’au {DATE_C:DD/MM/YYYY}'}
];let activeStamp=stamps[0].id,signatureData=null,outputActive=false;
const workspace=new FileWorkspace({queueEl:qs('#fileQueue'),onOpen:item=>loadItem(item)});
const annotations=new AnnotationManager({engine,layer:qs('#annotationLayer'),canvasWrap:qs('#pageCanvasWrap'),variables:vars});
const tools=new PDFTools({engine,annotations,variables:vars});
window.__NLAB_PDF_V1__={version:VERSION,engine,workspace,drive,variables:vars,annotations,tools};

function log(action,detail=''){history.unshift({time:new Date().toLocaleTimeString('fr-FR'),action,detail});history.splice(60);renderHistory()}
function renderHistory(){qs('#documentHistory').innerHTML=history.map(x=>'<div class="historyItem"><b>'+escapeHtml(x.action)+'</b><span>'+escapeHtml(x.time+(x.detail?' · '+x.detail:''))+'</span></div>').join('')}
function escapeHtml(s){return String(s??'').replace(/[&<>"]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[m]))}
function currentScope(){return qs('#pageScope').value}
function targetPages(){const p=engine.targetPages(currentScope());if(currentScope()==='selected'&&!p.length)toast('Cochez au moins une page');return p}
function markSection(id){const d=qs(id);if(d){d.open=true;d.scrollIntoView({behavior:'smooth',block:'start'})}}
function syncVariablesFromUi(){vars.set('INITIALS',qs('#operatorInitials').value.trim());for(const k of ['STAMP_DATE','DATE_A','DATE_B','DATE_C','DATE_D'])vars.set(k,qs('[data-date="'+k+'"]').value||today());syncNameFlags()}
function syncNameFlags(){vars.setOperation({ocr:qs('#suffixOcr').checked,dpi:qs('#suffixDpi').checked?Number(qs('#optDpi').value||150):vars.operation.dpi,jpeg:qs('#suffixJpeg').checked?Number(qs('#optJpeg').value||82):vars.operation.jpeg,gray:qs('#suffixGray').checked,annot:qs('#suffixAnnot').checked,fusion:qs('#suffixFusion').checked});updateNamePreview()}
function outputName(ext='.pdf'){syncVariablesFromUi();return vars.buildName(engine.fileName,{prefix:qs('#namePrefix').value,template:qs('#nameTemplate').value||'{FILENAME}',suffix:qs('#nameSuffix').value,extension:ext,operationSuffix:true})}
function updateNamePreview(){if(!qs('#namePreview'))return;qs('#namePreview').textContent=vars.buildName(engine.fileName,{prefix:qs('#namePrefix').value,template:qs('#nameTemplate').value||'{FILENAME}',suffix:qs('#nameSuffix').value,extension:'.pdf',operationSuffix:true})}
function renderVariables(){const keys=['FILENAME','DATE','TIME','DATETIME','INITIALS','STAMP_DATE','DATE_A','DATE_B','DATE_C','DATE_D','OP','DPI','JPEG'];qs('#variableGrid').innerHTML='';for(const k of keys){const c=document.createElement('code');c.textContent='{'+k+'}';c.title='Copier';c.onclick=async()=>{await navigator.clipboard?.writeText(c.textContent);toast(c.textContent+' copié')};qs('#variableGrid').append(c)}const grid=qs('#dateGrid');for(const k of ['STAMP_DATE','DATE_A','DATE_B','DATE_C','DATE_D']){const l=document.createElement('label');l.className='dateRow';l.innerHTML='<span>'+({STAMP_DATE:'Date tampon',DATE_A:'Date A',DATE_B:'Date B',DATE_C:'Date C',DATE_D:'Date D'}[k])+'</span><input type="date" data-date="'+k+'" value="'+today()+'">';grid.append(l)}qsa('[data-date]').forEach(x=>x.oninput=()=>{syncVariablesFromUi();renderStampLibrary()})}
function renderStampLibrary(){const box=qs('#stampLibrary');box.innerHTML='';for(const s of stamps){const row=document.createElement('div');row.className='stampPreset'+(s.id===activeStamp?' active':'');row.innerHTML='<button type="button">'+escapeHtml(s.label)+'</button><button type="button" title="Utiliser">✓</button>';row.querySelectorAll('button').forEach(b=>b.onclick=()=>{activeStamp=s.id;qs('#stampTemplate').value=s.template;renderStampLibrary()});box.append(row)}}
async function renderViewer(){if(!engine.pdfjs){qs('#emptyViewer').hidden=false;return}qs('#emptyViewer').hidden=true;const canvas=qs('#pageCanvas'),zoom=Number(qs('#viewerZoom').value||1),vp=await engine.renderPage(canvas,engine.currentPage,zoom),wrap=qs('#pageCanvasWrap');wrap.style.width=canvas.width+'px';wrap.style.height=canvas.height+'px';wrap.style.minWidth='0';qs('#annotationLayer').style.width=canvas.width+'px';qs('#annotationLayer').style.height=canvas.height+'px';qs('#pageInfo').textContent=engine.currentPage+' / '+engine.pageCount;qs('#zoomInfo').textContent=Math.round(zoom*100)+' %';qs('#docStatus').textContent=engine.fileName+' · '+engine.pageCount+' page(s)';annotations.render();updateNamePreview();await renderThumbs()}
async function renderThumbs(){const strip=qs('#pageStrip'),oldTop=strip.scrollLeft;strip.innerHTML='';for(let p=1;p<=engine.pageCount;p++){const t=document.createElement('div');t.className='pageThumb'+(p===engine.currentPage?' active':'')+(engine.selected.has(p)?' checked':'');t.dataset.page=p;const cb=document.createElement('input');cb.type='checkbox';cb.className='pageCheck';cb.checked=engine.selected.has(p);cb.setAttribute('aria-label','Sélectionner page '+p);cb.onclick=e=>e.stopPropagation();cb.onchange=e=>{engine.toggleSelected(p,e.target.checked);qs('#pageScope').value='selected'};const c=document.createElement('canvas'),lab=document.createElement('div');lab.className='pageThumbLabel';lab.textContent='Page '+p;t.append(cb,c,lab);t.onclick=e=>{if(e.target===cb)return;engine.selectPage(p)};strip.append(t);engine.renderThumb(c,p,.16).catch(()=>{})}strip.scrollLeft=oldTop;syncSelectionInfo()}
function syncSelectionInfo(){qs('#pageSelectionInfo').textContent=engine.selected.size+' / '+engine.pageCount+' page(s) cochée(s)';qsa('#pageStrip .pageThumb').forEach(t=>{const p=Number(t.dataset.page);t.classList.toggle('checked',engine.selected.has(p));const c=qs('.pageCheck',t);if(c)c.checked=engine.selected.has(p)})}
async function loadItem(item){try{await engine.loadFile(item.file);log('Ouverture',item.name);await renderViewer()}catch(e){toast(e.message);setStatus('Erreur : '+e.message)}}
function renderFileHistory(){const box=qs('#fileHistory');box.innerHTML=workspace.history.slice(0,20).map(x=>'<div class="historyItem"><b>'+escapeHtml(x.name)+'</b><span>'+new Date(x.time).toLocaleString('fr-FR')+'</span></div>').join('')}
async function saveFinal({driveOnly=false}={}){if(!engine.pdfDoc)throw new Error('Aucun PDF');const bytes=await annotations.exportBytes(),blob=new Blob([bytes],{type:'application/pdf'}),name=outputName('.pdf');if(driveOnly){if(!drive.connected)throw new Error('Connectez Google Drive');await drive.upload(blob,name,'exports');log('Drive export',name)}else{await workspace.writeBlob(blob,name,{mode:outputActive?qs('#outputMode').value:'download',operationFolder:qs('#operationFolder').value,granularity:qs('#archiveGranularity').value});log('Enregistrement',name)}return{name,blob,bytes}}
async function exportZip(){const {name,blob}=await saveFinal({driveOnly:false}),z=new JSZip();z.file(name,blob);z.file('config/pdf-studio-1.0.json',JSON.stringify(exportProfile(),null,2));z.file('config/stamps.json',JSON.stringify({schema:'nlab-pdf-stamps/v1',stamps},null,2));const out=await z.generateAsync({type:'blob',compression:'DEFLATE',compressionOptions:{level:6}}),zipName=name.replace(/\.pdf$/i,'')+'.zip';downloadBlob(out,zipName);log('ZIP',zipName)}
function exportProfile(){syncVariablesFromUi();return{schema:'nlab-pdf-studio/v1',version:VERSION,variables:vars.export(),naming:{prefix:qs('#namePrefix').value,template:qs('#nameTemplate').value,suffix:qs('#nameSuffix').value},output:{mode:qs('#outputMode').value,operationFolder:qs('#operationFolder').value,granularity:qs('#archiveGranularity').value},translation:{source:qs('#translationSource').value,target:qs('#translationTarget').value,layout:qs('#translationLayout').value,endpoint:qs('#translationEndpoint').value},stamps}}
function importProfile(d){if(d.variables)vars.import(d.variables);if(d.naming){qs('#namePrefix').value=d.naming.prefix||'';qs('#nameTemplate').value=d.naming.template||'{FILENAME}';qs('#nameSuffix').value=d.naming.suffix||''}if(d.output){qs('#outputMode').value=d.output.mode||'download';qs('#operationFolder').value=d.output.operationFolder||'TRAITEMENT';qs('#archiveGranularity').value=d.output.granularity||'month'}if(d.translation){qs('#translationSource').value=d.translation.source||'fr';qs('#translationTarget').value=d.translation.target||'en';qs('#translationLayout').value=d.translation.layout||'side-by-side';qs('#translationEndpoint').value=d.translation.endpoint||''}for(const k of ['STAMP_DATE','DATE_A','DATE_B','DATE_C','DATE_D']){const el=qs('[data-date="'+k+'"]');if(el)el.value=vars.values[k]||today()}qs('#operatorInitials').value=vars.values.INITIALS||'';updateNamePreview();toast('Configuration importée')}
function setupDrive(){const cfg=drive.config;qs('#googleClientId').value=cfg.clientId||'';qs('#googleApiKey').value=cfg.apiKey||'';qs('#googleAppId').value=cfg.appId||'';const update=()=>{const st=drive.state(),el=qs('#googleStatus');el.classList.toggle('connected',st.connected);el.textContent=st.connected?'Google Drive connecté'+(st.user?.email?' · '+st.user.email:''):'Mode local · Google Drive non connecté';qs('#disconnectGoogle').hidden=!st.connected;qs('#connectGoogle').hidden=st.connected};drive.addEventListener('state',update);update()}
async function chooseDriveDocument(){if(!drive.connected)await drive.connect();let file=null;try{file=await drive.pickAndDownload()}catch{const list=await drive.list('documents');if(!list.length)throw new Error('Aucun document dans Drive / nLab / PDF Studio / Documents');const lines=list.slice(0,30).map((x,i)=>(i+1)+' — '+x.name).join('\n'),n=Number(prompt('Choisissez un fichier Drive :\n'+lines,'1'));if(n>0&&n<=list.length)file=await drive.download(list[n-1].id,list[n-1].name,list[n-1].mimeType)}if(file){await workspace.addFiles([file]);workspace.setCurrent(workspace.items.at(-1).id);renderFileHistory()}}
function setupSignature(){let pad=null;const modal=qs('#signatureModal'),canvas=qs('#signatureCanvas');qs('#drawSignature').onclick=()=>{modal.hidden=false;pad=pad||new SignaturePad(canvas,{minWidth:1,maxWidth:2.5});pad.clear()};qs('#signatureClear').onclick=()=>pad?.clear();qs('#signatureCancel').onclick=()=>modal.hidden=true;qs('#signatureUse').onclick=()=>{if(!pad||pad.isEmpty())return toast('Dessinez une signature');signatureData=pad.toDataURL('image/png');annotations.setSignatureData(signatureData);renderSignaturePreview();modal.hidden=true};qs('#importSignature').onclick=()=>qs('#signatureInput').click();qs('#signatureInput').onchange=async e=>{const f=e.target.files?.[0];if(!f)return;signatureData=await fileDataUrl(f);annotations.setSignatureData(signatureData);renderSignaturePreview()};qs('#saveSignatureDrive').onclick=()=>run(async()=>{if(!signatureData)throw new Error('Aucune signature');if(!drive.connected)await drive.connect();const blob=await(await fetch(signatureData)).blob();await drive.upload(blob,'signature-'+Date.now()+'.png','signatures')});qs('#loadSignaturesDrive').onclick=()=>run(async()=>{if(!drive.connected)await drive.connect();const list=await drive.list('signatures');if(!list.length)throw new Error('Aucune signature Drive');const n=Number(prompt(list.slice(0,20).map((x,i)=>(i+1)+' — '+x.name).join('\n'),'1'));if(n>0&&n<=list.length){const f=await drive.download(list[n-1].id,list[n-1].name,list[n-1].mimeType);signatureData=await fileDataUrl(f);annotations.setSignatureData(signatureData);renderSignaturePreview()}})}
function renderSignaturePreview(){qs('#signaturePreview').innerHTML=signatureData?'<img src="'+signatureData+'" alt="Signature">':'<span class="hint">Aucune signature visuelle.</span>'}
async function fileDataUrl(f){return new Promise((res,rej)=>{const r=new FileReader();r.onload=()=>res(r.result);r.onerror=()=>rej(r.error);r.readAsDataURL(f)})}
async function run(fn){try{setStatus('Traitement…');await fn();setStatus('Prêt')}catch(e){console.error(e);toast(e.message||String(e),4000);setStatus('Erreur : '+(e.message||e))}}
function applyRibbonIcons(){const map={rbOpenFiles:['open','Fichiers'],rbOpenFolder:['folder','Dossier'],rbOpenDrive:['drive','Drive'],rbSave:['save','Enregistrer'],rbZip:['zip','ZIP'],rbDriveExport:['drive','Drive'],rbRotateLeft:['rotateL','Gauche'],rbRotateRight:['rotateR','Droite'],rbAddPage:['addPage','Page'],rbDeletePages:['trash','Suppr.'],rbText:['text','Texte'],rbStamp:['stamp','Tampon'],rbHighlight:['highlight','Surlign.'],rbSignature:['signature','Signature'],rbOcr:['ocr','OCR'],rbOptimize:['config','Optimiser'],rbTranslate:['translate','Traduire']};for(const[id,[ic,label]]of Object.entries(map)){const b=qs('#'+id);if(b)b.innerHTML=icon(ic)+'<span>'+label+'</span>'}}
async function signViaDss(){if(!engine.pdfDoc)throw new Error('Aucun PDF');const endpoint=qs('#dssEndpoint').value.trim();if(!endpoint)throw new Error('Endpoint DSS manquant');const bytes=await annotations.exportBytes(),form=new FormData();form.append('file',new Blob([bytes],{type:'application/pdf'}),outputName('.pdf'));const headers={};const token=qs('#dssToken').value.trim();if(token)headers.Authorization='Bearer '+token;const r=await fetch(endpoint,{method:'POST',headers,body:form});if(!r.ok)throw new Error('DSS HTTP '+r.status);const type=r.headers.get('content-type')||'';if(!type.includes('pdf')&&!type.includes('octet-stream'))throw new Error('Réponse DSS non PDF');const signed=new Uint8Array(await r.arrayBuffer());await engine.setBytes(signed);log('Signature DSS','PAdES externe');toast('PDF signé via DSS externe')}
function bind(){
 applyRibbonIcons();bindSidebar();bindSectionControls();wireMenuTabs();renderVariables();renderStampLibrary();renderFileHistory();setupDrive();setupSignature();updateNamePreview();
 engine.addEventListener('change',()=>renderViewer());engine.addEventListener('page',()=>renderViewer());engine.addEventListener('selection',()=>syncSelectionInfo());
 qs('#pickFiles').onclick=()=>qs('#filesInput').click();qs('#rbOpenFiles').onclick=()=>qs('#filesInput').click();qs('#filesInput').onchange=e=>run(async()=>{await workspace.chooseFiles(e.target.files);renderFileHistory();qs('#sourceInfo').textContent=workspace.items.length+' fichier(s) chargé(s)'});qs('#pickFolder').onclick=()=>run(async()=>{if(window.showDirectoryPicker)await workspace.chooseDirectory();else qs('#folderInput').click();renderFileHistory();qs('#sourceInfo').textContent=workspace.items.length+' fichier(s) chargé(s)'});qs('#rbOpenFolder').onclick=qs('#pickFolder').onclick;qs('#folderInput').onchange=e=>run(async()=>{await workspace.chooseFiles(e.target.files);renderFileHistory()});
 qs('#selectAllFiles').onclick=()=>workspace.setAll(true);qs('#selectNoneFiles').onclick=()=>workspace.setAll(false);qs('#loadSourcePreset').onclick=()=>run(async()=>{if(qs('#sourcePreset').value==='last'){await workspace.loadLastSource();renderFileHistory();qs('#sourceInfo').textContent='Source mémorisée : '+workspace.sourceHandle.name}else qs('#pickFiles').click()});
 qs('#pickDestination').onclick=()=>run(async()=>{const h=await workspace.chooseOutputDirectory();qs('#destinationInfo').textContent='Dossier : '+h.name});qs('#loadDestinationPreset').onclick=()=>run(async()=>{if(qs('#destinationPreset').value==='last'){const h=await workspace.loadLastOutput();qs('#destinationInfo').textContent='Sortie mémorisée : '+h.name}else qs('#pickDestination').click()});qs('#activateOutput').onclick=()=>{outputActive=true;const m=qs('#outputMode').value;qs('#outputModeStatus').textContent=m==='same-source'?'Sortie activée : même dossier que la source (si accès dossier disponible).':'Sortie activée : '+m;toast('Mode de sortie activé')};
 qs('#savePdf').onclick=()=>run(()=>saveFinal());qs('#rbSave').onclick=qs('#savePdf').onclick;qs('#exportZip').onclick=()=>run(exportZip);qs('#rbZip').onclick=qs('#exportZip').onclick;qs('#saveDrive').onclick=()=>run(()=>saveFinal({driveOnly:true}));qs('#rbDriveExport').onclick=qs('#saveDrive').onclick;
 ['namePrefix','nameTemplate','nameSuffix','suffixOcr','suffixDpi','suffixJpeg','suffixGray','suffixAnnot','suffixFusion','operatorInitials','optDpi','optJpeg'].forEach(id=>qs('#'+id)?.addEventListener('input',syncNameFlags));
 qs('#pageScope').onchange=syncSelectionInfo;qs('#selectAllPages').onclick=()=>engine.selectAll();qs('#selectNonePages').onclick=()=>engine.selectNone();
 qs('#rotateLeft').onclick=()=>run(async()=>{const p=targetPages();if(p.length){await engine.rotate(p,-90);log('Rotation gauche',p.join(','))}});qs('#rotateRight').onclick=()=>run(async()=>{const p=targetPages();if(p.length){await engine.rotate(p,90);log('Rotation droite',p.join(','))}});qs('#rbRotateLeft').onclick=qs('#rotateLeft').onclick;qs('#rbRotateRight').onclick=qs('#rotateRight').onclick;
 qs('#addBlank').onclick=()=>run(async()=>{await engine.addBlank();log('Nouvelle page')});qs('#rbAddPage').onclick=qs('#addBlank').onclick;qs('#duplicatePage').onclick=()=>run(async()=>{await engine.duplicate();log('Duplication page')});qs('#deletePages').onclick=()=>run(async()=>{const p=targetPages();if(p.length){await engine.deletePages(p);log('Suppression pages',p.join(','))}});qs('#rbDeletePages').onclick=qs('#deletePages').onclick;
 qs('#extractPages').onclick=()=>run(async()=>{const p=targetPages();if(!p.length)return;const b=await engine.extractPages(p),name=safeName(engine.fileName.replace(/\.pdf$/i,''))+'_extrait.pdf';await workspace.writeBlob(new Blob([b],{type:'application/pdf'}),name,{mode:'download'});log('Extraction',p.join(','))});
 qs('#mergeSelectedFiles').onclick=()=>run(async()=>{await engine.mergeFiles(workspace.selected().map(x=>x.file));qs('#suffixFusion').checked=true;syncNameFlags();log('Fusion PDF',workspace.selected().length+' fichier(s)')});
 qs('#firstPage').onclick=()=>engine.selectPage(1);qs('#prevPage').onclick=()=>engine.selectPage(engine.currentPage-1);qs('#nextPage').onclick=()=>engine.selectPage(engine.currentPage+1);qs('#lastPage').onclick=()=>engine.selectPage(engine.pageCount);
 qs('#viewerZoom').oninput=()=>renderViewer();qs('#zoomOut').onclick=()=>{qs('#viewerZoom').value=Math.max(.3,+qs('#viewerZoom').value-.1);renderViewer()};qs('#zoomIn').onclick=()=>{qs('#viewerZoom').value=Math.min(2.5,+qs('#viewerZoom').value+.1);renderViewer()};qs('#fitWidth').onclick=()=>run(async()=>{if(!engine.pdfjs)return;const p=await engine.pdfjs.getPage(engine.currentPage),vp=p.getViewport({scale:1}),z=Math.max(.3,(qs('#canvasStage').clientWidth-50)/vp.width);qs('#viewerZoom').value=Math.min(2.5,z);renderViewer()});qs('#fitPage').onclick=()=>run(async()=>{if(!engine.pdfjs)return;const p=await engine.pdfjs.getPage(engine.currentPage),vp=p.getViewport({scale:1}),s=qs('#canvasStage'),z=Math.min((s.clientWidth-50)/vp.width,(s.clientHeight-50)/vp.height);qs('#viewerZoom').value=Math.max(.3,Math.min(2.5,z));renderViewer()});
 qs('#thumbZoom').oninput=e=>{document.documentElement.style.setProperty('--thumb-zoom',e.target.value);qs('#thumbZoomInfo').textContent=Math.round(e.target.value*100)+' %'};qs('#thumbZoomOut').onclick=()=>{qs('#thumbZoom').value=Math.max(.65,+qs('#thumbZoom').value-.1);qs('#thumbZoom').dispatchEvent(new Event('input'))};qs('#thumbZoomIn').onclick=()=>{qs('#thumbZoom').value=Math.min(2.2,+qs('#thumbZoom').value+.1);qs('#thumbZoom').dispatchEvent(new Event('input'))};qs('#thumbLeft').onclick=()=>qs('#pageStrip').scrollBy({left:-Math.max(260,qs('#pageStrip').clientWidth*.7),behavior:'smooth'});qs('#thumbRight').onclick=()=>qs('#pageStrip').scrollBy({left:Math.max(260,qs('#pageStrip').clientWidth*.7),behavior:'smooth'});
 qsa('.toolBtn').forEach(b=>b.onclick=()=>annotations.setTool(b.dataset.tool));qs('#rbText').onclick=()=>annotations.setTool('text');qs('#rbHighlight').onclick=()=>annotations.setTool('highlight');qs('#rbStamp').onclick=()=>markSection('#sectionStamps');qs('#rbSignature').onclick=()=>annotations.setTool('signature');qs('#deleteSelectedAnnotation').onclick=()=>annotations.deleteSelected();qs('#imageInput').onchange=async e=>{const f=e.target.files?.[0];if(f){annotations.setImageData(await fileDataUrl(f));annotations.setTool('image');toast('Cliquez dans la page pour placer l’image')}};
 qs('#addStampCurrent').onclick=()=>{syncVariablesFromUi();annotations.addStamp(engine.currentPage,+qs('#stampX').value,+qs('#stampY').value,qs('#stampTemplate').value);log('Tampon','page '+engine.currentPage)};qs('#addStampScope').onclick=()=>{syncVariablesFromUi();const p=targetPages();if(p.length){annotations.addStampScope(p,+qs('#stampX').value,+qs('#stampY').value,qs('#stampTemplate').value);log('Tampon multi-pages',p.join(','))}};
 qs('#exportStamps').onclick=()=>jsonDownload({schema:'nlab-pdf-stamps/v1',stamps},'nLab-PDF-Stamps.json');qs('#importStamps').onclick=()=>qs('#stampsInput').click();qs('#stampsInput').onchange=async e=>{const d=await readJsonFile(e.target.files[0]);if(Array.isArray(d.stamps)){stamps.splice(0,stamps.length,...d.stamps);renderStampLibrary();toast('Tampons importés')}};
 qs('#runOcr').onclick=()=>run(async()=>{const p=targetPages();if(!p.length)return;const txt=await tools.ocr(p,{lang:qs('#ocrLang').value,dpi:+qs('#optDpi').value,onProgress:m=>setStatus('OCR p'+m.page+' · '+Math.round((m.progress||0)*100)+' %')});qs('#ocrResult').value=txt;qs('#suffixOcr').checked=true;syncNameFlags();log('OCR',p.join(','))});qs('#rbOcr').onclick=qs('#runOcr').onclick;
 qs('#runOptimize').onclick=()=>run(async()=>{const p=targetPages();if(!p.length)return;await tools.optimize(p,{dpi:+qs('#optDpi').value,jpeg:+qs('#optJpeg').value,gray:qs('#optGray').value==='1'});qs('#suffixDpi').checked=qs('#suffixJpeg').checked=true;qs('#suffixGray').checked=qs('#optGray').value==='1';syncNameFlags();log('Optimisation',p.join(','))});qs('#rbOptimize').onclick=qs('#runOptimize').onclick;
 qs('#runTranslation').onclick=()=>run(async()=>{const p=targetPages();if(!p.length)return;qs('#translationStatus').textContent='Traduction en cours…';const b=await tools.bilingual({source:qs('#translationSource').value,target:qs('#translationTarget').value,layout:qs('#translationLayout').value,endpoint:qs('#translationEndpoint').value.trim(),pages:p}),name=safeName(engine.fileName.replace(/\.pdf$/i,''))+'_bilingue.pdf';await workspace.writeBlob(new Blob([b],{type:'application/pdf'}),name,{mode:'download'});qs('#translationStatus').textContent='PDF bilingue créé : '+name;log('Traduction',p.join(','))});qs('#rbTranslate').onclick=()=>markSection('#sectionTranslation');
 qs('#importConfig').onclick=()=>qs('#configInput').click();qs('#configInput').onchange=async e=>importProfile(await readJsonFile(e.target.files[0]));qs('#exportConfig').onclick=()=>jsonDownload(exportProfile(),'nLab-PDF-Studio-1.0-config.json');
 qs('#saveGoogleConfig').onclick=()=>{drive.configure({clientId:qs('#googleClientId').value.trim(),apiKey:qs('#googleApiKey').value.trim(),appId:qs('#googleAppId').value.trim()});toast('Configuration Google enregistrée')};qs('#connectGoogle').onclick=()=>run(()=>drive.connect());qs('#disconnectGoogle').onclick=()=>drive.disconnect();qs('#rbOpenDrive').onclick=()=>run(chooseDriveDocument);qs('#openDriveDocuments').onclick=qs('#rbOpenDrive').onclick;qs('#openDriveExports').onclick=()=>run(async()=>{if(!drive.connected)await drive.connect();await drive.ensureStructure();drive.openFolder('exports')});
 qs('#runDss').onclick=()=>run(signViaDss);
 qsa('.studioMenu button').forEach(b=>b.addEventListener('click',()=>{if(b.dataset.tab==='file')markSection('#sectionInput');if(b.dataset.tab==='tools')markSection('#sectionOcr');if(b.dataset.tab==='connection')markSection('#sectionConfig');if(b.dataset.tab==='view')qs('#canvasStage').scrollIntoView({behavior:'smooth'});if(b.dataset.tab==='help')alert('PDF Studio 1.0\n\nBase Studio commune nLab. Utilisez Configuration, Entrée, Sortie et la portée des pages. Les cases en haut à gauche des vignettes servent à la sélection multi-pages.')}));qs('#runDiagnostics').onclick=runDiagnostics;
 runDiagnostics()
}
function runDiagnostics(){const visible=id=>{const e=qs(id);if(!e)return false;const s=getComputedStyle(e);return s.display!=='none'&&s.visibility!=='hidden'};const rows=[['Logo nLab',!!qs('.studioBrand img')],['Configuration 0',visible('#sectionConfig')],['Connexion',visible('#connectGoogle')||visible('#disconnectGoogle')],['Entrée manuelle',qs('#sourcePreset')?.value==='manual'],['Sortie manuelle',qs('#destinationPreset')?.value==='manual'],['Portée pages',visible('#pageScope')],['Zoom vignettes',visible('#thumbZoom')],['Scroll horizontal vignettes',visible('#pageStrip')],['Panneau redimensionnable',!!qs('#sidebarResizer')],['5 dates',qsa('[data-date]').length===5],['PDF.js',!!window.pdfjsLib],['PDF-Lib',!!window.PDFLib],['JSZip',!!window.JSZip],['Tesseract',!!window.Tesseract],['Aucun runtime 0.9.x',!qsa('script[src*="runtime09"]').length]];if(engine.pageCount)rows.push(['Cases par vignette',qsa('#pageStrip .pageCheck').length===engine.pageCount]);qs('#diagnosticList').innerHTML=rows.map(([n,ok])=>'<div class="'+(ok?'diagOk':'diagBad')+'">'+(ok?'✅ ':'❌ ')+escapeHtml(n)+'</div>').join('');return rows.every(x=>x[1])}
bind();
