import{qs,qsa,toast,setStatus,bindSidebar,bindSectionControls,wireMenuTabs,jsonDownload,readJsonFile,today,downloadBlob,safeName}from'../../_shared/studio-v1/core.js';
import{VariableEngine}from'../../_shared/studio-v1/variables.js';
import{FileWorkspace}from'../../_shared/studio-v1/file-io.js';
import{DriveService}from'../../_shared/studio-v1/drive.js';
import{PDFEngine}from'./pdf-engine.js';
import{AnnotationManager}from'./annotations.js';
import{PDFTools}from'./pdf-tools.js';
import{AdvancedPDFTools}from'./advanced-tools.js';
import{icon}from'../../_shared/studio-v1/icons.js';
import{ActionHistory}from'../../_shared/studio-v1/history.js';
import{STUDIO_TEMPLATE_PRESETS,presetBy}from'../../_shared/studio-v1/templates.js';
import{DocumentConversion}from'./document-conversion.js';

const VERSION='1.0.0 TEST',vars=new VariableEngine(),engine=new PDFEngine(),drive=new DriveService({storageKey:'nlab-pdf-studio-v1-google'});
const historyStore=new ActionHistory({storageKey:'nlab-pdf-studio-v1-actions',limit:250});
const stamps=STUDIO_TEMPLATE_PRESETS.stamp.map(x=>({...x}));
let activeStamp=stamps[0].id,signatureData=null,outputActive=false;
const workspace=new FileWorkspace({queueEl:qs('#fileQueue'),onOpen:item=>loadItem(item),onSelectionChange:renderSelectedFiles,onLoad:renderSelectedFiles});
const annotations=new AnnotationManager({engine,layer:qs('#annotationLayer'),canvasWrap:qs('#pageCanvasWrap'),variables:vars});
const tools=new PDFTools({engine,annotations,variables:vars}),advanced=new AdvancedPDFTools({engine,annotations,variables:vars});
const conversion=new DocumentConversion({engine,workspace,variables:vars});
window.__NLAB_PDF_V1__={version:VERSION,engine,workspace,drive,variables:vars,annotations,tools,advanced,conversion,history:historyStore};

function log(action,detail='',meta={}){historyStore.add(action,detail,meta);renderHistory()}
function renderHistory(){const box=qs('#documentHistory');if(box)box.innerHTML=historyStore.list(250).map(x=>'<div class="historyItem"><b>'+escapeHtml(x.action)+'</b><span>'+escapeHtml(new Date(x.at).toLocaleString('fr-FR')+(x.detail?' · '+x.detail:''))+'</span></div>').join('')}
function escapeHtml(s){return String(s??'').replace(/[&<>"]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[m]))}
function renderSelectedFiles(){const selected=workspace.selected(),all=workspace.items;vars.setRuntime({SELECTED_COUNT:selected.length});const n=qs('#selectedFilesCount'),box=qs('#selectedFilesSummary');if(n)n.textContent=selected.length+' / '+all.length;if(box)box.textContent=selected.length?selected.slice(0,12).map(x=>'✓ '+x.name).join('\n')+(selected.length>12?'\n… +'+(selected.length-12):''):'Aucun fichier sélectionné.';updateNamePreview()}
function currentScope(){return qs('#pageScope').value}
function targetPages(){const p=engine.targetPages(currentScope());if(currentScope()==='selected'&&!p.length)toast('Cochez au moins une page');return p}
function markSection(id){const d=qs(id);if(d){d.open=true;d.scrollIntoView({behavior:'smooth',block:'start'})}}
function extDot(name=''){const m=String(name).match(/(\.[^.]+)$/);return m?m[1]:''}
function currentStamp(){return stamps.find(s=>s.id===activeStamp)||stamps[0]}
function applyStampNaming(){const s=currentStamp();vars.setRuntime({STAMP_ID:s.id,STAMP_LABEL:s.label,STAMP_PREFIX:qs('#stampApplyNaming')?.checked?(qs('#stampNamePrefix')?.value||s.filenamePrefix||''):'',STAMP_SUFFIX:qs('#stampApplyNaming')?.checked?(qs('#stampNameSuffix')?.value||s.filenameSuffix||''):''});vars.setOperation({stamp:true,annot:true});updateNamePreview()}
function syncVariablesFromUi(){
 const map={INITIALS:'operatorInitials',CLIENT:'globalClient',PROJECT:'globalProject',REFERENCE:'globalReference',SITE:'globalSite',SERVICE:'globalService',CATEGORY:'globalCategory',TAG:'globalTag',TREATMENT:'globalTreatment'};
 for(const[k,id]of Object.entries(map)){const el=qs('#'+id);if(el)vars.set(k,el.value.trim())}
 for(const k of ['STAMP_DATE','DATE_A','DATE_B','DATE_C','DATE_D'])vars.set(k,qs('[data-date="'+k+'"]')?.value||today());
 vars.setRuntime({PAGE:engine.currentPage||'',PAGES:engine.pageCount||'',SELECTED_COUNT:workspace.selected().length,SOURCE:(qs('#sourceProvider')?.value||'local').toUpperCase(),OUTPUT:(qs('#outputProvider')?.value||'local').toUpperCase()});
 if(qs('#operationFolder'))qs('#operationFolder').value=vars.values.TREATMENT||'TRAITEMENT';
 syncNameFlags()
}
function syncNameFlags(){vars.setOperation({ocr:qs('#suffixOcr')?.checked,dpi:qs('#suffixDpi')?.checked?Number(qs('#optDpi')?.value||150):null,jpeg:qs('#suffixJpeg')?.checked?Number(qs('#optJpeg')?.value||82):null,gray:qs('#suffixGray')?.checked,annot:qs('#suffixAnnot')?.checked||vars.operation.annot,fusion:qs('#suffixFusion')?.checked,stamp:vars.operation.stamp});updateNamePreview()}
function nameForFile(fileName,ext=extDot(fileName)||'.pdf'){
 const sp={prefix:vars.runtime.STAMP_PREFIX||'',suffix:vars.runtime.STAMP_SUFFIX||''},mode=qs('#namingMode')?.value||'classic';
 if(mode==='code')return vars.buildName(fileName,{prefix:sp.prefix,template:qs('#nameCodeTemplate')?.value||'{FILENAME}',suffix:sp.suffix,extension:ext,operationSuffix:true});
 return vars.buildName(fileName,{prefix:(qs('#namePrefix')?.value||'')+sp.prefix,template:qs('#nameTemplate')?.value||'{FILENAME}',suffix:(qs('#nameSuffix')?.value||'')+sp.suffix,extension:ext,operationSuffix:true})
}
function outputName(ext='.pdf'){syncVariablesFromUi();return nameForFile(engine.fileName,ext)}
function updateNamePreview(){const el=qs('#namePreview');if(el)el.textContent=nameForFile(engine.fileName,'.pdf')}
function renderVariables(){const keys=['FILENAME','FULLNAME','EXT','FOLDER','PATH','RELATIVE_PATH','DATE','TIME','DATETIME','YEAR','MONTH','DAY','WEEK','PAGE','PAGES','SELECTED_COUNT','INITIALS','CLIENT','PROJECT','REFERENCE','SITE','SERVICE','CATEGORY','TAG','TREATMENT','STAMP_DATE','DATE_A','DATE_B','DATE_C','DATE_D','STAMP_ID','STAMP_LABEL','STAMP_PREFIX','STAMP_SUFFIX','SOURCE','OUTPUT','OP','DPI','JPEG'];const box=qs('#variableGrid');box.innerHTML='';for(const k of keys){const el=document.createElement('code');el.textContent='{'+k+'}';el.title='Copier';el.onclick=async()=>{await navigator.clipboard?.writeText(el.textContent);toast(el.textContent+' copié')};box.append(el)}const grid=qs('#dateGrid');grid.innerHTML='';for(const k of ['STAMP_DATE','DATE_A','DATE_B','DATE_C','DATE_D']){const l=document.createElement('label');l.className='dateRow';l.innerHTML='<span>'+({STAMP_DATE:'Date tampon',DATE_A:'Date A',DATE_B:'Date B',DATE_C:'Date C',DATE_D:'Date D'}[k])+'</span><input type="date" data-date="'+k+'" value="'+(vars.values[k]||today())+'">';grid.append(l)}qsa('[data-date]').forEach(x=>x.oninput=()=>syncVariablesFromUi())}
function renderStampLibrary(){const box=qs('#stampLibrary');box.innerHTML='';for(const s of stamps){const row=document.createElement('div');row.className='stampPreset'+(s.id===activeStamp?' active':'');row.innerHTML='<button type="button">'+escapeHtml(s.label)+'</button><button type="button" title="Utiliser">✓</button>';row.querySelectorAll('button').forEach(b=>b.onclick=()=>{activeStamp=s.id;qs('#stampTemplate').value=s.template;qs('#stampNamePrefix').value=s.filenamePrefix||'';qs('#stampNameSuffix').value=s.filenameSuffix||'';renderStampLibrary();showRibbonContext('stamp')});box.append(row)}}
let renderGeneration=0,renderTimer=0;
function scheduleViewerRender(){clearTimeout(renderTimer);const gen=++renderGeneration;renderTimer=setTimeout(()=>renderViewer(gen),0)}
async function renderSelectableText(page,viewport,gen){
 const layer=qs('#textLayer');if(!layer||!engine.pdfjs||!viewport)return;
 layer.innerHTML='';layer.style.width=viewport.width+'px';layer.style.height=viewport.height+'px';layer.style.setProperty('--scale-factor',String(viewport.scale));
 if(typeof pdfjsLib.renderTextLayer!=='function')return;
 const p=await engine.pdfjs.getPage(page),tc=await p.getTextContent();if(gen!==renderGeneration)return;
 try{const task=pdfjsLib.renderTextLayer({textContentSource:tc,container:layer,viewport,textDivs:[]});await task?.promise}catch(e){console.debug('Text layer:',e?.message||e)}
}
async function renderViewer(gen=++renderGeneration){if(!engine.pdfjs){qs('#emptyViewer').hidden=false;return}qs('#emptyViewer').hidden=true;const canvas=qs('#pageCanvas'),zoom=Number(qs('#viewerZoom').value||1),vp=await engine.renderPage(canvas,engine.currentPage,zoom);if(gen!==renderGeneration)return;await renderSelectableText(engine.currentPage,vp,gen);if(gen!==renderGeneration)return;const wrap=qs('#pageCanvasWrap');wrap.style.width=canvas.width+'px';wrap.style.height=canvas.height+'px';wrap.style.minWidth='0';qs('#annotationLayer').style.width=canvas.width+'px';qs('#annotationLayer').style.height=canvas.height+'px';qs('#pageInfo').textContent=engine.currentPage+' / '+engine.pageCount;qs('#zoomInfo').textContent=Math.round(zoom*100)+' %';qs('#docStatus').textContent=engine.fileName+' · '+engine.pageCount+' page(s)';annotations.render();updateNamePreview();renderThumbs()}
function renderThumbs(){const strip=qs('#pageStrip'),oldTop=strip.scrollLeft;strip.innerHTML='';for(let p=1;p<=engine.pageCount;p++){const t=document.createElement('div');t.className='pageThumb'+(p===engine.currentPage?' active':'')+(engine.selected.has(p)?' checked':'');t.dataset.page=p;const cb=document.createElement('input');cb.type='checkbox';cb.className='pageCheck';cb.checked=engine.selected.has(p);cb.setAttribute('aria-label','Sélectionner page '+p);cb.onclick=e=>e.stopPropagation();cb.onchange=e=>{engine.toggleSelected(p,e.target.checked);qs('#pageScope').value='selected'};const c=document.createElement('canvas'),lab=document.createElement('div');lab.className='pageThumbLabel';lab.textContent='Page '+p;t.append(cb,c,lab);t.onclick=e=>{if(e.target===cb)return;engine.selectPage(p)};strip.append(t);engine.renderThumb(c,p,.16).catch(()=>{})}strip.scrollLeft=oldTop;syncSelectionInfo()}
function syncSelectionInfo(){qs('#pageSelectionInfo').textContent=engine.selected.size+' / '+engine.pageCount+' page(s) cochée(s)';qsa('#pageStrip .pageThumb').forEach(t=>{const p=Number(t.dataset.page);t.classList.toggle('checked',engine.selected.has(p));const c=qs('.pageCheck',t);if(c)c.checked=engine.selected.has(p)})}
async function loadItem(item){try{const rel=item.relativePath||item.name||'',parts=rel.split('/');vars.setRuntime({FOLDER:parts.length>1?parts.at(-2):'',PATH:rel,RELATIVE_PATH:rel,FILESIZE:item.file?.size||0});await engine.loadFile(item.file);vars.setRuntime({PAGE:engine.currentPage,PAGES:engine.pageCount});log('Ouverture',item.name);scheduleViewerRender()}catch(e){toast(e.message);setStatus('Erreur : '+e.message)}}
function renderFileHistory(){const box=qs('#fileHistory');if(box)box.innerHTML=workspace.history.slice(0,20).map(x=>'<div class="historyItem"><b>'+escapeHtml(x.name)+'</b><span>'+new Date(x.time).toLocaleString('fr-FR')+'</span></div>').join('')}
function structureTemplate(id=qs('#outputStructure')?.value||'root'){
 const t={root:'',treatment:'{TREATMENT}','year-month':'{YEAR}/{MONTH}','year-month-week':'{YEAR}/{MONTH}/S{WEEK}','treatment-date':'{TREATMENT}/{YEAR}/{MONTH}'};
 return id==='custom'?(qs('#outputPathTemplate')?.value||''):t[id]??''
}
function syncOutputUi(){
 const provider=qs('#outputProvider')?.value||'local',structure=qs('#outputStructure')?.value||'root',preset=structureTemplate(structure),path=qs('#outputPathTemplate');
 if(path&&structure!=='custom')path.value=preset;
 let mode='download';
 if(provider==='source')mode=structure==='root'?'same-source':'same-source-custom';
 else if(provider==='local')mode=structure==='root'?'manual-root':'custom-path';
 else if(provider==='download')mode='download';
 else if(provider==='drive')mode='drive';
 if(qs('#outputMode'))qs('#outputMode').value=['same-source','same-source-custom','custom-path','manual-root','download'].includes(mode)?mode:'download';
 vars.setRuntime({OUTPUT:provider.toUpperCase()});
 return{provider,structure,mode,pathTemplate:vars.resolve(structure==='custom'?(path?.value||''):preset,engine.fileName),operationFolder:vars.values.TREATMENT||'TRAITEMENT'}
}
function outputOptions(){syncVariablesFromUi();const o=syncOutputUi();return{mode:o.mode,pathTemplate:o.pathTemplate,operationFolder:o.operationFolder,granularity:qs('#archiveGranularity')?.value||'month'}}
async function saveBlobConfigured(blob,name,{forceDrive=false}={}){
 const out=syncOutputUi();
 if(forceDrive||out.provider==='drive'){if(!drive.connected)throw new Error('Connectez Google Drive');await drive.upload(blob,name,'exports');log('Drive export',name,{provider:'drive'});return{kind:'drive',name}}
 const r=await workspace.writeBlob(blob,name,outputActive?outputOptions():{mode:'download'});log(r.kind==='download'?'Téléchargement':'Enregistrement',name,{provider:out.provider,path:out.pathTemplate});return r
}
function batchRenameRows(){syncVariablesFromUi();return workspace.selected().map((x,i)=>{vars.setRuntime({INDEX:i+1,PATH:x.relativePath||x.name,RELATIVE_PATH:x.relativePath||x.name,FILESIZE:x.file?.size||0});return{item:x,name:nameForFile(x.name,extDot(x.name))}})}
function previewRenameSelection(){const rows=batchRenameRows(),box=qs('#renameBatchPreview');if(box)box.textContent=rows.length?rows.slice(0,20).map(x=>x.item.name+' → '+x.name).join('\n'):'Aucun fichier coché.';return rows}
async function exportRenamedZip(){const rows=batchRenameRows();if(!rows.length)throw new Error('Aucun fichier coché');const z=new JSZip();for(const r of rows)z.file(r.name,r.item.file);const blob=await z.generateAsync({type:'blob',compression:'DEFLATE',compressionOptions:{level:6}}),name=vars.resolve('{DATE:YYYY-MM-DD}_fichiers-renommes.zip',engine.fileName);await saveBlobConfigured(blob,name);log('Renommage en lot',rows.length+' fichier(s)');return{name,blob}}
function applyNamingPreset(id){const p=presetBy('naming',id);if(!p)return;qs('#namingMode').value='code';qs('#nameCodeTemplate').value=p.template;qs('#namingCodeField').hidden=false;qs('#namingClassic').hidden=true;updateNamePreview();previewRenameSelection()}
function applyHeaderPreset(kind,id){const p=presetBy(kind,id);if(!p)return;if(kind==='header'){qs('#headerLeft').value=p.left||'';qs('#headerTemplate').value=p.center||'';qs('#headerRight').value=p.right||''}else{qs('#footerLeft').value=p.left||'';qs('#footerTemplate').value=p.center||'';qs('#footerRight').value=p.right||''}}
async function saveFinal({driveOnly=false}={}){if(!engine.pdfDoc)throw new Error('Aucun PDF');const bytes=await annotations.exportBytes(),blob=new Blob([bytes],{type:'application/pdf'}),name=outputName('.pdf');await saveBlobConfigured(blob,name,{forceDrive:driveOnly});return{name,blob,bytes}}
async function exportZip(){if(!engine.pdfDoc)throw new Error('Aucun PDF');const bytes=await annotations.exportBytes(),name=outputName('.pdf'),z=new JSZip();z.file(name,new Blob([bytes],{type:'application/pdf'}));z.file('config/pdf-studio-1.0.json',JSON.stringify(exportProfile(),null,2));z.file('config/stamps.json',JSON.stringify({schema:'nlab-pdf-stamps/v1',stamps},null,2));const out=await z.generateAsync({type:'blob',compression:'DEFLATE',compressionOptions:{level:6}}),zipName=name.replace(/\.pdf$/i,'')+'.zip';await saveBlobConfigured(out,zipName);log('ZIP',zipName);return{blob:out,name:zipName}}
function exportProfile(){syncVariablesFromUi();return{schema:'nlab-pdf-studio/v1',version:VERSION,variables:vars.export(),naming:{mode:qs('#namingMode')?.value||'classic',preset:qs('#namingPreset')?.value||'original',prefix:qs('#namePrefix')?.value||'',template:qs('#nameTemplate')?.value||'{FILENAME}',suffix:qs('#nameSuffix')?.value||'',code:qs('#nameCodeTemplate')?.value||'{FILENAME}'},output:{provider:qs('#outputProvider')?.value||'local',structure:qs('#outputStructure')?.value||'root',pathTemplate:qs('#outputPathTemplate')?.value||'',mode:qs('#outputMode')?.value||'download'},headerFooter:{headerLeft:qs('#headerLeft')?.value||'',header:qs('#headerTemplate')?.value||'',headerRight:qs('#headerRight')?.value||'',footerLeft:qs('#footerLeft')?.value||'',footer:qs('#footerTemplate')?.value||'',footerRight:qs('#footerRight')?.value||'',qr:qs('#headerFooterQr')?.value||'',qrPosition:qs('#headerFooterQrPos')?.value||'none',qrSize:Number(qs('#headerFooterQrSize')?.value||38)},translation:{source:qs('#translationSource').value,target:qs('#translationTarget').value,layout:qs('#translationLayout').value,endpoint:qs('#translationEndpoint').value},stamps}}
function importProfile(d){
 if(d?.variables)vars.import(d.variables);
 const n=d?.naming||{};if(qs('#namingMode'))qs('#namingMode').value=n.mode||'classic';if(qs('#namingPreset'))qs('#namingPreset').value=n.preset||'original';if(qs('#namePrefix'))qs('#namePrefix').value=n.prefix||'';if(qs('#nameTemplate'))qs('#nameTemplate').value=n.template||'{FILENAME}';if(qs('#nameSuffix'))qs('#nameSuffix').value=n.suffix||'';if(qs('#nameCodeTemplate'))qs('#nameCodeTemplate').value=n.code||'{FILENAME}';
 const o=d?.output||{};if(qs('#outputProvider'))qs('#outputProvider').value=o.provider||'local';if(qs('#outputStructure'))qs('#outputStructure').value=o.structure||'root';if(qs('#outputPathTemplate'))qs('#outputPathTemplate').value=o.pathTemplate||'{TREATMENT}';
 const hf=d?.headerFooter||{};for(const [id,key]of [['headerLeft','headerLeft'],['headerTemplate','header'],['headerRight','headerRight'],['footerLeft','footerLeft'],['footerTemplate','footer'],['footerRight','footerRight'],['headerFooterQr','qr']])if(qs('#'+id)&&hf[key]!=null)qs('#'+id).value=hf[key];if(qs('#headerFooterQrPos')&&hf.qrPosition)qs('#headerFooterQrPos').value=hf.qrPosition;if(qs('#headerFooterQrSize')&&hf.qrSize)qs('#headerFooterQrSize').value=hf.qrSize;
 if(d?.translation){qs('#translationSource').value=d.translation.source||'fr';qs('#translationTarget').value=d.translation.target||'en';qs('#translationLayout').value=d.translation.layout||'side-by-side';qs('#translationEndpoint').value=d.translation.endpoint||''}
 const importedValues=d?.variables?.values||d?.variables||{},map={INITIALS:'operatorInitials',CLIENT:'globalClient',PROJECT:'globalProject',REFERENCE:'globalReference',SITE:'globalSite',SERVICE:'globalService',CATEGORY:'globalCategory',TAG:'globalTag',TREATMENT:'globalTreatment'};for(const[k,id]of Object.entries(map)){if(importedValues[k]!=null)vars.set(k,importedValues[k]);if(qs('#'+id))qs('#'+id).value=vars.values[k]||''}
 for(const k of ['STAMP_DATE','DATE_A','DATE_B','DATE_C','DATE_D']){if(importedValues[k]!=null)vars.set(k,importedValues[k]);const el=qs('[data-date="'+k+'"]');if(el)el.value=vars.values[k]||today()}
 const code=qs('#namingMode')?.value==='code';if(qs('#namingCodeField'))qs('#namingCodeField').hidden=!code;if(qs('#namingClassic'))qs('#namingClassic').hidden=code;syncOutputUi();syncNameFlags();previewRenameSelection();requestAnimationFrame(updateNamePreview);toast('Configuration importée')
}
function setupDrive(){const cfg=drive.config;qs('#googleClientId').value=cfg.clientId||'';qs('#googleApiKey').value=cfg.apiKey||'';qs('#googleAppId').value=cfg.appId||'';const update=()=>{const st=drive.state(),el=qs('#googleStatus');el.classList.toggle('connected',st.connected);el.textContent=st.connected?'Google Drive connecté'+(st.user?.email?' · '+st.user.email:''):'Mode local · Google Drive non connecté';qs('#disconnectGoogle').hidden=!st.connected;qs('#connectGoogle').hidden=st.connected};drive.addEventListener('state',update);update()}
async function chooseDriveDocument(){if(!drive.connected)await drive.connect();let file=null;try{file=await drive.pickAndDownload()}catch{const list=await drive.list('documents');if(!list.length)throw new Error('Aucun document dans Drive / nLab / PDF Studio / Documents');const lines=list.slice(0,30).map((x,i)=>(i+1)+' — '+x.name).join('\n'),n=Number(prompt('Choisissez un fichier Drive :\n'+lines,'1'));if(n>0&&n<=list.length)file=await drive.download(list[n-1].id,list[n-1].name,list[n-1].mimeType)}if(file){await workspace.addFiles([file]);workspace.setCurrent(workspace.items.at(-1).id);renderFileHistory()}}
function setupSignature(){let pad=null;const modal=qs('#signatureModal'),canvas=qs('#signatureCanvas');qs('#drawSignature').onclick=()=>{modal.hidden=false;pad=pad||new SignaturePad(canvas,{minWidth:1,maxWidth:2.5});pad.clear()};qs('#signatureClear').onclick=()=>pad?.clear();qs('#signatureCancel').onclick=()=>modal.hidden=true;qs('#signatureUse').onclick=()=>{if(!pad||pad.isEmpty())return toast('Dessinez une signature');signatureData=pad.toDataURL('image/png');annotations.setSignatureData(signatureData);renderSignaturePreview();modal.hidden=true};qs('#importSignature').onclick=()=>qs('#signatureInput').click();qs('#signatureInput').onchange=async e=>{const f=e.target.files?.[0];if(!f)return;signatureData=await fileDataUrl(f);annotations.setSignatureData(signatureData);renderSignaturePreview()};qs('#saveSignatureDrive').onclick=()=>run(async()=>{if(!signatureData)throw new Error('Aucune signature');if(!drive.connected)await drive.connect();const blob=await(await fetch(signatureData)).blob();await drive.upload(blob,'signature-'+Date.now()+'.png','signatures')});qs('#loadSignaturesDrive').onclick=()=>run(async()=>{if(!drive.connected)await drive.connect();const list=await drive.list('signatures');if(!list.length)throw new Error('Aucune signature Drive');const n=Number(prompt(list.slice(0,20).map((x,i)=>(i+1)+' — '+x.name).join('\n'),'1'));if(n>0&&n<=list.length){const f=await drive.download(list[n-1].id,list[n-1].name,list[n-1].mimeType);signatureData=await fileDataUrl(f);annotations.setSignatureData(signatureData);renderSignaturePreview()}})}
function renderSignaturePreview(){qs('#signaturePreview').innerHTML=signatureData?'<img src="'+signatureData+'" alt="Signature">':'<span class="hint">Aucune signature visuelle.</span>'}
async function fileDataUrl(f){return new Promise((res,rej)=>{const r=new FileReader();r.onload=()=>res(r.result);r.onerror=()=>rej(r.error);r.readAsDataURL(f)})}
async function run(fn){try{setStatus('Traitement…');await fn();setStatus('Prêt')}catch(e){console.error(e);toast(e.message||String(e),4000);setStatus('Erreur : '+(e.message||e))}}
function applyRibbonIcons(){const map={rbOpenFiles:['open','Fichiers'],rbOpenFolder:['folder','Dossier'],rbOpenDrive:['drive','Drive'],rbSave:['save','Enregistrer'],rbZip:['zip','ZIP'],rbDriveExport:['drive','Drive'],rbRotateLeft:['rotateL','Gauche'],rbRotateRight:['rotateR','Droite'],rbAddPage:['addPage','Page'],rbDeletePages:['trash','Suppr.'],rbText:['text','Texte'],rbStamp:['stamp','Tampon'],rbHighlight:['highlight','Surlign.'],rbSignature:['signature','Signature'],rbOcr:['ocr','OCR'],rbOptimize:['config','Optimiser'],rbTranslate:['translate','Traduire']};for(const[id,[ic,label]]of Object.entries(map)){const b=qs('#'+id);if(b)b.innerHTML=icon(ic)+'<span>'+label+'</span>'}}
async function signViaDss(){if(!engine.pdfDoc)throw new Error('Aucun PDF');const endpoint=qs('#dssEndpoint').value.trim();if(!endpoint)throw new Error('Endpoint DSS manquant');const bytes=await annotations.exportBytes(),form=new FormData();form.append('file',new Blob([bytes],{type:'application/pdf'}),outputName('.pdf'));const headers={};const token=qs('#dssToken').value.trim();if(token)headers.Authorization='Bearer '+token;const r=await fetch(endpoint,{method:'POST',headers,body:form});if(!r.ok)throw new Error('DSS HTTP '+r.status);const type=r.headers.get('content-type')||'';if(!type.includes('pdf')&&!type.includes('octet-stream'))throw new Error('Réponse DSS non PDF');const signed=new Uint8Array(await r.arrayBuffer());engine.pageAnnotations.clear();await engine.setBytes(signed);engine.dispatchEvent(new Event('annotations'));log('Signature DSS','PAdES externe');toast('PDF signé via DSS externe')}
async function qrDataUrl(text){
 if(!window.QRCode)throw new Error('Bibliothèque QR indisponible');const host=document.createElement('div');host.style.cssText='position:fixed;left:-9999px;top:-9999px';document.body.append(host);
 new QRCode(host,{text:String(text||''),width:256,height:256,colorDark:'#000000',colorLight:'#ffffff',correctLevel:QRCode.CorrectLevel.M});
 await new Promise(r=>setTimeout(r,40));const canvas=host.querySelector('canvas'),img=host.querySelector('img'),url=canvas?canvas.toDataURL('image/png'):img?.src;host.remove();if(!url)throw new Error('QR non généré');return url
}
function barcodeDataUrl(text){if(!window.JsBarcode)throw new Error('Bibliothèque code-barres indisponible');const canvas=document.createElement('canvas');JsBarcode(canvas,String(text||''),{format:'CODE128',displayValue:true,margin:8,height:80});return canvas.toDataURL('image/png')}
function advancedStatusCompare(r){return 'PDF A : '+r.left.pages+' page(s) · PDF B : '+r.right.pages+' page(s) · similarité moyenne '+Math.round(r.average*100)+' %\n'+r.rows.map(x=>'p.'+x.page+' : '+Math.round(x.similarity*100)+' % · '+x.status).join('\n')}
function bind(){
 applyRibbonIcons();bindSidebar();bindSectionControls();wireMenuTabs();renderVariables();renderStampLibrary();renderFileHistory();setupDrive();setupSignature();updateNamePreview();
 engine.addEventListener('change',scheduleViewerRender);engine.addEventListener('page',scheduleViewerRender);engine.addEventListener('selection',()=>syncSelectionInfo());
 qs('#pickFiles').onclick=()=>qs('#filesInput').click();qs('#rbOpenFiles').onclick=()=>qs('#filesInput').click();qs('#filesInput').onchange=e=>run(async()=>{await workspace.chooseFiles(e.target.files);renderFileHistory();qs('#sourceInfo').textContent=workspace.items.length+' fichier(s) chargé(s)'});qs('#pickFolder').onclick=()=>run(async()=>{if(window.showDirectoryPicker)await workspace.chooseDirectory();else qs('#folderInput').click();renderFileHistory();qs('#sourceInfo').textContent=workspace.items.length+' fichier(s) chargé(s)'});qs('#rbOpenFolder').onclick=qs('#pickFolder').onclick;qs('#folderInput').onchange=e=>run(async()=>{await workspace.chooseFiles(e.target.files);renderFileHistory()});
 qs('#selectAllFiles').onclick=()=>workspace.setAll(true);qs('#selectNoneFiles').onclick=()=>workspace.setAll(false);qs('#loadSourcePreset').onclick=()=>run(async()=>{if(qs('#sourcePreset').value==='last'){await workspace.loadLastSource();renderFileHistory();qs('#sourceInfo').textContent='Source mémorisée : '+workspace.sourceHandle.name}else qs('#pickFiles').click()});
 qs('#pickDestination').onclick=()=>run(async()=>{const h=await workspace.chooseOutputDirectory();qs('#destinationInfo').textContent='Dossier : '+h.name});qs('#loadDestinationPreset').onclick=()=>run(async()=>{if(qs('#destinationPreset').value==='last'){const h=await workspace.loadLastOutput();qs('#destinationInfo').textContent='Sortie mémorisée : '+h.name}else qs('#pickDestination').click()});qs('#activateOutput').onclick=()=>{outputActive=true;const m=qs('#outputMode').value;qs('#outputModeStatus').textContent=m==='same-source'?'Sortie activée : même dossier que la source (si accès dossier disponible).':'Sortie activée : '+m;toast('Mode de sortie activé')};
 qs('#savePdf').onclick=()=>run(()=>saveFinal());qs('#rbSave').onclick=qs('#savePdf').onclick;qs('#exportZip').onclick=()=>run(exportZip);qs('#rbZip').onclick=qs('#exportZip').onclick;qs('#saveDrive').onclick=()=>run(()=>saveFinal({driveOnly:true}));qs('#rbDriveExport').onclick=qs('#saveDrive').onclick;
 ['namePrefix','nameTemplate','nameSuffix','suffixOcr','suffixDpi','suffixJpeg','suffixGray','suffixAnnot','suffixFusion','operatorInitials','optDpi','optJpeg'].forEach(id=>qs('#'+id)?.addEventListener('input',syncNameFlags));
 qs('#pageScope').onchange=syncSelectionInfo;qs('#selectAllPages').onclick=()=>engine.selectAll();qs('#selectNonePages').onclick=()=>engine.selectNone();
 qs('#rotateLeft').onclick=()=>run(async()=>{const p=targetPages();if(p.length){await engine.rotate(p,-90);log('Rotation gauche',p.join(','))}});qs('#rotateRight').onclick=()=>run(async()=>{const p=targetPages();if(p.length){await engine.rotate(p,90);log('Rotation droite',p.join(','))}});qs('#rbRotateLeft').onclick=qs('#rotateLeft').onclick;qs('#rbRotateRight').onclick=qs('#rotateRight').onclick;
 qs('#addBlank').onclick=()=>run(async()=>{await engine.addBlank();log('Nouvelle page')});qs('#rbAddPage').onclick=qs('#addBlank').onclick;qs('#duplicatePage').onclick=()=>run(async()=>{await engine.duplicate();log('Duplication page')});qs('#deletePages').onclick=()=>run(async()=>{const p=targetPages();if(p.length){await engine.deletePages(p);log('Suppression pages',p.join(','))}});qs('#rbDeletePages').onclick=qs('#deletePages').onclick;
 qs('#extractPages').onclick=()=>run(async()=>{const p=targetPages();if(!p.length)return;const b=await engine.extractPages(p),name=safeName(engine.fileName.replace(/\.pdf$/i,''))+'_extrait.pdf';await workspace.writeBlob(new Blob([b],{type:'application/pdf'}),name,{mode:'download'});log('Extraction',p.join(','))});
 qs('#mergeSelectedFiles').onclick=()=>run(async()=>{await engine.mergeFiles(workspace.selected().map(x=>x.file));qs('#suffixFusion').checked=true;syncNameFlags();log('Fusion PDF',workspace.selected().length+' fichier(s)')});
 qs('#firstPage').onclick=()=>engine.selectPage(1);qs('#prevPage').onclick=()=>engine.selectPage(engine.currentPage-1);qs('#nextPage').onclick=()=>engine.selectPage(engine.currentPage+1);qs('#lastPage').onclick=()=>engine.selectPage(engine.pageCount);
 qs('#viewerZoom').oninput=scheduleViewerRender;qs('#zoomOut').onclick=()=>{qs('#viewerZoom').value=Math.max(.3,+qs('#viewerZoom').value-.1);scheduleViewerRender()};qs('#zoomIn').onclick=()=>{qs('#viewerZoom').value=Math.min(2.5,+qs('#viewerZoom').value+.1);scheduleViewerRender()};qs('#fitWidth').onclick=()=>run(async()=>{if(!engine.pdfjs)return;const p=await engine.pdfjs.getPage(engine.currentPage),vp=p.getViewport({scale:1}),z=Math.max(.3,(qs('#canvasStage').clientWidth-50)/vp.width);qs('#viewerZoom').value=Math.min(2.5,z);scheduleViewerRender()});qs('#fitPage').onclick=()=>run(async()=>{if(!engine.pdfjs)return;const p=await engine.pdfjs.getPage(engine.currentPage),vp=p.getViewport({scale:1}),s=qs('#canvasStage'),z=Math.min((s.clientWidth-50)/vp.width,(s.clientHeight-50)/vp.height);qs('#viewerZoom').value=Math.max(.3,Math.min(2.5,z));scheduleViewerRender()});
 qs('#thumbZoom').oninput=e=>{document.documentElement.style.setProperty('--thumb-zoom',e.target.value);qs('#thumbZoomInfo').textContent=Math.round(e.target.value*100)+' %'};qs('#thumbZoomOut').onclick=()=>{qs('#thumbZoom').value=Math.max(.65,+qs('#thumbZoom').value-.1);qs('#thumbZoom').dispatchEvent(new Event('input'))};qs('#thumbZoomIn').onclick=()=>{qs('#thumbZoom').value=Math.min(2.2,+qs('#thumbZoom').value+.1);qs('#thumbZoom').dispatchEvent(new Event('input'))};qs('#thumbLeft').onclick=()=>qs('#pageStrip').scrollBy({left:-Math.max(260,qs('#pageStrip').clientWidth*.7),behavior:'smooth'});qs('#thumbRight').onclick=()=>qs('#pageStrip').scrollBy({left:Math.max(260,qs('#pageStrip').clientWidth*.7),behavior:'smooth'});
 qsa('.toolBtn').forEach(b=>b.onclick=()=>annotations.setTool(b.dataset.tool));qs('#rbText').onclick=()=>annotations.setTool('text');qs('#rbHighlight').onclick=()=>annotations.setTool('highlight');qs('#rbStamp').onclick=()=>markSection('#sectionStamps');qs('#rbSignature').onclick=()=>annotations.setTool('signature');qs('#deleteSelectedAnnotation').onclick=()=>annotations.deleteSelected();qs('#imageInput').onchange=async e=>{const f=e.target.files?.[0];if(f){annotations.setImageData(await fileDataUrl(f));annotations.setTool('image');toast('Cliquez dans la page pour placer l’image')}};
 qs('#addStampCurrent').onclick=()=>{syncVariablesFromUi();annotations.addStamp(engine.currentPage,+qs('#stampX').value,+qs('#stampY').value,qs('#stampTemplate').value);log('Tampon','page '+engine.currentPage)};qs('#addStampScope').onclick=()=>{syncVariablesFromUi();const p=targetPages();if(p.length){annotations.addStampScope(p,+qs('#stampX').value,+qs('#stampY').value,qs('#stampTemplate').value);log('Tampon multi-pages',p.join(','))}};
 qs('#exportStamps').onclick=()=>jsonDownload({schema:'nlab-pdf-stamps/v1',stamps},'nLab-PDF-Stamps.json');qs('#importStamps').onclick=()=>qs('#stampsInput').click();qs('#stampsInput').onchange=async e=>{const d=await readJsonFile(e.target.files[0]);if(Array.isArray(d.stamps)){stamps.splice(0,stamps.length,...d.stamps);renderStampLibrary();toast('Tampons importés')}};
 qs('#runOcr').onclick=()=>run(async()=>{const p=targetPages();if(!p.length)return;const txt=await tools.ocr(p,{lang:qs('#ocrLang').value,dpi:+qs('#optDpi').value,onProgress:m=>setStatus('OCR p'+m.page+' · '+Math.round((m.progress||0)*100)+' %')});qs('#ocrResult').value=txt;qs('#suffixOcr').checked=true;syncNameFlags();log('OCR',p.join(','))});qs('#rbOcr').onclick=qs('#runOcr').onclick;
 qs('#runOptimize').onclick=()=>run(async()=>{const p=targetPages();if(!p.length)return;await tools.optimize(p,{dpi:+qs('#optDpi').value,jpeg:+qs('#optJpeg').value,gray:qs('#optGray').value==='1'});qs('#suffixDpi').checked=qs('#suffixJpeg').checked=true;qs('#suffixGray').checked=qs('#optGray').value==='1';syncNameFlags();log('Optimisation',p.join(','))});qs('#rbOptimize').onclick=qs('#runOptimize').onclick;
 qs('#runTranslation').onclick=()=>run(async()=>{const p=targetPages();if(!p.length)return;qs('#translationStatus').textContent='Traduction en cours…';const b=await tools.bilingual({source:qs('#translationSource').value,target:qs('#translationTarget').value,layout:qs('#translationLayout').value,endpoint:qs('#translationEndpoint').value.trim(),pages:p}),name=safeName(engine.fileName.replace(/\.pdf$/i,''))+'_bilingue.pdf';await workspace.writeBlob(new Blob([b],{type:'application/pdf'}),name,{mode:'download'});qs('#translationStatus').textContent='PDF bilingue créé : '+name;log('Traduction',p.join(','))});qs('#rbTranslate').onclick=()=>markSection('#sectionTranslation');
 qs('#importConfig').onclick=()=>qs('#configInput').click();qs('#configInput').onchange=async e=>importProfile(await readJsonFile(e.target.files[0]));qs('#exportConfig').onclick=()=>jsonDownload(exportProfile(),'nLab-PDF-Studio-1.0-config.json');
 qs('#saveGoogleConfig').onclick=()=>{drive.configure({clientId:qs('#googleClientId').value.trim(),apiKey:qs('#googleApiKey').value.trim(),appId:qs('#googleAppId').value.trim()});toast('Configuration Google enregistrée')};qs('#connectGoogle').onclick=()=>run(()=>drive.connect());qs('#disconnectGoogle').onclick=()=>drive.disconnect();qs('#rbOpenDrive').onclick=()=>run(chooseDriveDocument);qs('#openDriveDocuments').onclick=qs('#rbOpenDrive').onclick;qs('#openDriveExports').onclick=()=>run(async()=>{if(!drive.connected)await drive.connect();await drive.ensureStructure();drive.openFolder('exports')});
 qs('#addQr').onclick=()=>run(async()=>{if(!engine.pdfDoc)throw new Error('Aucun PDF');const url=await qrDataUrl(qs('#codeValue').value);annotations.addImage(engine.currentPage,70,8,url,'image');annotations.render();log('QR','page '+engine.currentPage)});
 qs('#addBarcode').onclick=()=>run(async()=>{if(!engine.pdfDoc)throw new Error('Aucun PDF');const url=barcodeDataUrl(qs('#codeValue').value);annotations.addImage(engine.currentPage,60,12,url,'image');annotations.render();log('Code-barres','page '+engine.currentPage)});
 qs('#applyHeaderFooter').onclick=()=>run(async()=>{syncVariablesFromUi();const p=targetPages();if(p.length){await advanced.headerFooter(p,{header:qs('#headerTemplate').value,footer:qs('#footerTemplate').value});log('En-tête/pied',p.join(','))}});
 qs('#cropPages').onclick=()=>run(async()=>{const p=targetPages();if(p.length){await advanced.cropPages(p,{left:+qs('#cropLeft').value,right:+qs('#cropRight').value,top:+qs('#cropTop').value,bottom:+qs('#cropBottom').value});log('Recadrage',p.join(','))}});
 qs('#pdfToPng').onclick=()=>run(()=>advanced.downloadPageImage(engine.currentPage,{type:'png'}));qs('#pdfToJpg').onclick=()=>run(()=>advanced.downloadPageImage(engine.currentPage,{type:'jpg'}));
 qs('#pdfToPngZip').onclick=()=>run(async()=>{const p=targetPages();if(!p.length)return;const b=await advanced.allImagesZip({type:'png',pages:p});downloadBlob(b,safeName(engine.fileName.replace(/\.pdf$/i,''))+'_PNG.zip');log('PDF→PNG ZIP',p.join(','))});
 qs('#pdfToJpgZip').onclick=()=>run(async()=>{const p=targetPages();if(!p.length)return;const b=await advanced.allImagesZip({type:'jpg',pages:p});downloadBlob(b,safeName(engine.fileName.replace(/\.pdf$/i,''))+'_JPG.zip');log('PDF→JPG ZIP',p.join(','))});
 qs('#inspectForms').onclick=()=>run(async()=>{const fields=advanced.inspectForms();qs('#formStatus').textContent=fields.length?fields.map(x=>x.name+' · '+x.type+(x.value!==''?' = '+x.value:'')).join('\n'):'Aucun champ AcroForm.'});
 qs('#addFormField').onclick=()=>run(async()=>{const name=qs('#newFormFieldName').value.trim()||('Champ_'+Date.now());await advanced.addTextField(engine.currentPage,name);qs('#formStatus').textContent='Champ ajouté : '+name;log('Champ formulaire',name)});
 qs('#fillForms').onclick=()=>run(async()=>{const d=JSON.parse(qs('#formValues').value||'{}');await advanced.fillForms(d);qs('#formStatus').textContent='Réponses appliquées.';log('Formulaire rempli')});
 qs('#flattenForms').onclick=()=>run(async()=>{await advanced.flattenForms();qs('#formStatus').textContent='Formulaire aplati.';log('Formulaire aplati')});
 qs('#redactionTool').onclick=()=>{annotations.setTool('redaction');toast('Cliquez dans la page pour placer une zone de caviardage')};
 qs('#applyRedactions').onclick=()=>run(async()=>{const p=targetPages();if(p.length){await advanced.applySecureRedactions(p,{dpi:+qs('#optDpi').value||150});log('Caviardage définitif',p.join(','));toast('Caviardage rasterisé appliqué')}});
 qs('#pickCompare').onclick=()=>qs('#compareInput').click();qs('#compareInput').onchange=e=>run(async()=>{const file=e.target.files?.[0];if(!file)return;const r=await advanced.compare(file);qs('#compareStatus').textContent=advancedStatusCompare(r);log('Comparaison',file.name)});
 qs('#batchCleanMetadata').onclick=()=>run(async()=>{const files=workspace.selected().map(x=>x.file).filter(f=>/\.pdf$/i.test(f.name));if(!files.length)throw new Error('Aucun PDF coché');const b=await advanced.batchCleanMetadata(files);downloadBlob(b,'nLab-PDF-batch-metadata-clean.zip');log('Batch métadonnées',files.length+' PDF')});
 qs('#inspectSignatureStructure').onclick=()=>{const s=advanced.signatureStructure();qs('#securityStatus').textContent=(s.hasSignature?'Signature(s) structurelle(s) détectée(s)':'Aucune structure de signature détectée')+' · /Sig: '+s.sigCount+' · ByteRange: '+s.byteRanges.length+'\n'+s.note};
 qs('#cleanMetadata').onclick=()=>run(async()=>{await advanced.cleanMetadata();qs('#securityStatus').textContent='Métadonnées descriptives nettoyées. Créateur/Producteur = nLab PDF Studio 1.0.';log('Nettoyage métadonnées')});
 qs('#runDss').onclick=()=>run(signViaDss);
 qsa('.studioMenu button').forEach(b=>b.addEventListener('click',()=>{if(b.dataset.tab==='file')markSection('#sectionInput');if(b.dataset.tab==='tools')markSection('#sectionOcr');if(b.dataset.tab==='connection')markSection('#sectionConfig');if(b.dataset.tab==='view')qs('#canvasStage').scrollIntoView({behavior:'smooth'});if(b.dataset.tab==='help')alert('PDF Studio 1.0\n\nBase Studio commune nLab. Utilisez Configuration, Entrée, Sortie et la portée des pages. Les cases en haut à gauche des vignettes servent à la sélection multi-pages.')}));qs('#runDiagnostics').onclick=runDiagnostics;
 runDiagnostics()
}
function runDiagnostics(){const visible=id=>{const e=qs(id);if(!e)return false;const s=getComputedStyle(e);return s.display!=='none'&&s.visibility!=='hidden'};const rows=[['Logo nLab',!!qs('.studioBrand img')],['Configuration 0',visible('#sectionConfig')],['Connexion',visible('#connectGoogle')||visible('#disconnectGoogle')],['Entrée manuelle',qs('#sourcePreset')?.value==='manual'],['Sortie manuelle',qs('#destinationPreset')?.value==='manual'],['Portée pages',visible('#pageScope')],['Zoom vignettes',visible('#thumbZoom')],['Scroll horizontal vignettes',visible('#pageStrip')],['Panneau redimensionnable',!!qs('#sidebarResizer')],['5 dates',qsa('[data-date]').length===5],['PDF.js',!!window.pdfjsLib],['PDF-Lib',!!window.PDFLib],['JSZip',!!window.JSZip],['Tesseract',!!window.Tesseract],['QR',!!window.QRCode],['Code-barres',!!window.JsBarcode],['Outils PDF avancés',!!advanced],['Aucun runtime 0.9.x',!qsa('script[src*="runtime09"]').length]];if(engine.pageCount)rows.push(['Cases par vignette',qsa('#pageStrip .pageCheck').length===engine.pageCount]);qs('#diagnosticList').innerHTML=rows.map(([n,ok])=>'<div class="'+(ok?'diagOk':'diagBad')+'">'+(ok?'✅ ':'❌ ')+escapeHtml(n)+'</div>').join('');return rows.every(x=>x[1])}
bind();
