const esc=s=>String(s??'').replace(/[&<>"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]));
const bytes=n=>{n=Number(n)||0;if(n<1024)return n+' o';if(n<1048576)return(n/1024).toFixed(n<10240?1:0)+' Ko';return(n/1048576).toFixed(1)+' Mo'};
const ext=n=>(String(n||'').toLowerCase().match(/\.([a-z0-9]+)$/)?.[1]||'');
export class CollectionBrowser extends EventTarget{
 constructor({host,view='list',key='collection',getThumbnail=null}={}){
  super();this.host=host;this.key=key;this.items=[];this.selected=new Set();this.activeId=null;
  this.view=localStorage.getItem('nlab-studio-v2-'+key+'-view')||view;this.sortMode=localStorage.getItem('nlab-studio-v2-'+key+'-sort')||'name';this.sortDirection=Number(localStorage.getItem('nlab-studio-v2-'+key+'-dir')||1);this.groupBy=localStorage.getItem('nlab-studio-v2-'+key+'-group')||'none';this.getThumbnail=getThumbnail;this.groupState=this.loadGroupState()
 }
 loadGroupState(){try{return JSON.parse(localStorage.getItem('nlab-studio-v2-'+this.key+'-groups')||'{}')}catch{return{}}}
 saveGroupState(){localStorage.setItem('nlab-studio-v2-'+this.key+'-groups',JSON.stringify(this.groupState))}
 normalize(x,i){const data=x.data??x,f=data?.file||data;return{id:x.id||('item-'+i),label:x.label||x.name||f?.name||('Élément '+(i+1)),subtitle:x.subtitle||x.type||'',thumb:x.thumb||'',data,size:x.size??f?.size??0,type:x.type||f?.type||'',extension:x.extension||ext(x.label||x.name||f?.name),pages:x.pages??x.meta?.pages??null,relativePath:x.relativePath||data?.relativePath||f?.webkitRelativePath||'',meta:{...(x.meta||{})}}}
 setItems(items=[]){const prior=this.activeId;this.items=items.map((x,i)=>this.normalize(x,i));this.selected=new Set([...this.selected].filter(id=>this.items.some(x=>x.id===id)));this.activeId=this.items.some(x=>x.id===prior)?prior:(this.items[0]?.id||null);this.sort(false);this.render();return this}
 updateItem(id,patch={}){const x=this.items.find(i=>i.id===id);if(!x)return null;Object.assign(x,patch);this.render();return x}
 setView(view){this.view=['list','grid','thumbs'].includes(view)?view:'list';localStorage.setItem('nlab-studio-v2-'+this.key+'-view',this.view);this.render()}
 setSort(mode='name',direction=1){this.sortMode=mode;this.sortDirection=direction<0?-1:1;localStorage.setItem('nlab-studio-v2-'+this.key+'-sort',this.sortMode);localStorage.setItem('nlab-studio-v2-'+this.key+'-dir',String(this.sortDirection));this.sort();this.render()}
 sort(render=true){const d=this.sortDirection,mode=this.sortMode;this.items.sort((a,b)=>{let r=0;if(mode==='size')r=a.size-b.size;else if(mode==='type')r=a.extension.localeCompare(b.extension,'fr');else if(mode==='path')r=(a.relativePath||a.label).localeCompare(b.relativePath||b.label,'fr');else if(mode==='pages')r=(a.pages||0)-(b.pages||0);else if(mode==='selected')r=Number(this.selected.has(b.id))-Number(this.selected.has(a.id));else r=a.label.localeCompare(b.label,'fr');return r*d});if(render)this.render();return this.items}
 setGroupBy(mode='none'){this.groupBy=['none','path','type','pages','selected'].includes(mode)?mode:'none';localStorage.setItem('nlab-studio-v2-'+this.key+'-group',this.groupBy);this.render()}
 toggleGroup(key){this.groupState[key]=!(this.groupState[key]!==false);this.saveGroupState();this.render()}
 collapseGroups(){const keys=[...new Set(this.items.map(x=>this.groupKey(x)).filter(Boolean))];for(const k of keys)this.groupState[k]=false;this.saveGroupState();this.render()}
 expandGroups(){const keys=[...new Set(this.items.map(x=>this.groupKey(x)).filter(Boolean))];for(const k of keys)this.groupState[k]=true;this.saveGroupState();this.render()}
 select(id,on=true){on?this.selected.add(id):this.selected.delete(id);this.dispatchEvent(new CustomEvent('selection',{detail:this.selectedItems()}));this.render()}
 selectAll(){this.selected=new Set(this.items.map(x=>x.id));this.dispatchEvent(new CustomEvent('selection',{detail:this.selectedItems()}));this.render()}
 clearSelection(){this.selected.clear();this.dispatchEvent(new CustomEvent('selection',{detail:[]}));this.render()}
 selectedItems(){return this.items.filter(x=>this.selected.has(x.id))}
 active(){return this.items.find(x=>x.id===this.activeId)||null}
 activate(id){this.activeId=id;const item=this.active();this.dispatchEvent(new CustomEvent('activate',{detail:item}));this.render();return item}
 navigationItems(selectedOnly=false){const a=selectedOnly?this.selectedItems():this.items;return a.length?a:this.items}
 previous({selectedOnly=false}={}){const a=this.navigationItems(selectedOnly);if(!a.length)return null;let i=a.findIndex(x=>x.id===this.activeId);if(i<0)i=0;return this.activate(a[(i-1+a.length)%a.length].id)}
 next({selectedOnly=false}={}){const a=this.navigationItems(selectedOnly);if(!a.length)return null;let i=a.findIndex(x=>x.id===this.activeId);if(i<0)i=-1;return this.activate(a[(i+1)%a.length].id)}
 groupKey(x){if(this.groupBy==='type')return(x.extension||'sans extension').toUpperCase();if(this.groupBy==='selected')return this.selected.has(x.id)?'Sélectionnés':'Non sélectionnés';if(this.groupBy==='pages')return x.pages?x.pages+' page'+(x.pages>1?'s':''):'Pages inconnues';if(this.groupBy==='path'){const p=x.relativePath||x.label,parts=p.split('/');return parts.length>1?parts.slice(0,-1).join('/'):'Racine'}return''}
 metaText(x){const a=[];if(x.size)a.push(bytes(x.size));if(x.pages)a.push(x.pages+' p.');if(x.extension)a.push(x.extension.toUpperCase());return a.join(' · ')}
 itemHtml(x){return '<article class="collectionItem '+(x.id===this.activeId?'active':'')+'" data-collection-id="'+esc(x.id)+'"><label class="collectionCheck" title="Sélectionner"><input type="checkbox" data-collection-select="'+esc(x.id)+'" '+(this.selected.has(x.id)?'checked':'')+'></label><div class="collectionThumb" data-thumb-id="'+esc(x.id)+'">'+(x.thumb?'<img src="'+esc(x.thumb)+'" alt="">':'<span class="collectionThumbPlaceholder"></span>')+'</div><button type="button" data-collection-open="'+esc(x.id)+'"><strong>'+esc(x.label)+'</strong><small>'+esc(x.subtitle||x.relativePath||'')+'</small><em>'+esc(this.metaText(x))+'</em></button></article>'}
 render(){if(!this.host)return;this.host.className='collectionBrowser collection-'+this.view;const groups=new Map();for(const x of this.items){const k=this.groupKey(x);if(!groups.has(k))groups.set(k,[]);groups.get(k).push(x)}
  this.host.innerHTML=this.items.length?[...groups].map(([k,list])=>{if(!k)return list.map(x=>this.itemHtml(x)).join('');const open=this.groupState[k]!==false;return '<section class="collectionGroup '+(open?'':'collapsed')+'" data-collection-group="'+esc(k)+'"><button class="collectionGroupHead" type="button" data-group-toggle="'+esc(k)+'" aria-expanded="'+(open?'true':'false')+'"><span>'+esc(k)+'</span><small>'+list.length+'</small><b>'+ (open?'▾':'▸') +'</b></button><div class="collectionGroupBody" '+(open?'':'hidden')+'>'+list.map(x=>this.itemHtml(x)).join('')+'</div></section>'}).join(''):'<div class="collectionEmpty">Aucun élément.</div>';
  this.host.querySelectorAll('[data-collection-select]').forEach(cb=>cb.onchange=()=>this.select(cb.dataset.collectionSelect,cb.checked));this.host.querySelectorAll('[data-collection-open]').forEach(b=>b.onclick=()=>this.activate(b.dataset.collectionOpen));this.host.querySelectorAll('[data-group-toggle]').forEach(b=>b.onclick=()=>this.toggleGroup(b.dataset.groupToggle));this.loadThumbs()
 }
 loadThumbs(){if(!this.getThumbnail)return;const nodes=[...this.host.querySelectorAll('[data-thumb-id]')].filter(n=>!n.querySelector('img'));const load=async n=>{const x=this.items.find(i=>i.id===n.dataset.thumbId);if(!x||x.thumb)return;try{const r=await this.getThumbnail(x);if(r?.url){x.thumb=r.url;if(r.pages&&!x.pages)x.pages=r.pages;if(n.isConnected)n.innerHTML='<img src="'+esc(r.url)+'" alt="">';const card=n.closest('.collectionItem');const em=card?.querySelector('em');if(em)em.textContent=this.metaText(x)}}catch(e){if(n.isConnected)n.innerHTML='<span class="collectionThumbPlaceholder" title="'+esc(e?.message||'Aperçu indisponible')+'">!</span>'}};
  if('IntersectionObserver'in window){const io=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting){load(e.target);io.unobserve(e.target)}}),{root:this.host,rootMargin:'300px'});nodes.forEach(n=>io.observe(n))}else nodes.forEach(load)}
}
