const DRIVE_SCOPE='https://www.googleapis.com/auth/drive.file https://www.googleapis.com/auth/userinfo.email';
async function jsonOrError(r){const t=await r.text();let d={};try{d=t?JSON.parse(t):{}}catch{}if(!r.ok)throw new Error(d.error?.message||d.error_description||('HTTP '+r.status));return d}
export class DriveService extends EventTarget{
 constructor({storageKey='nlab-studio-v2-google'}={}){super();this.storageKey=storageKey;this.token='';this.expiresAt=0;this.user=null;this.folders={};try{this.config=JSON.parse(localStorage.getItem(storageKey)||'{}')}catch{this.config={}}}
 configure(cfg={}){this.config={...this.config,...cfg};localStorage.setItem(this.storageKey,JSON.stringify(this.config));this.dispatchEvent(new Event('state'));return this}
 get connected(){return!!this.token&&Date.now()<this.expiresAt-30000}
 state(){return{connected:this.connected,user:this.user,folders:this.folders,config:{...this.config,clientSecret:undefined}}}
 async connect(){const clientId=String(this.config.clientId||'').trim();if(!clientId)throw new Error('Client ID OAuth Web Google manquant.');if(!window.google?.accounts?.oauth2)throw new Error('Google Identity Services non chargé.');return new Promise((resolve,reject)=>{const c=google.accounts.oauth2.initTokenClient({client_id:clientId,scope:DRIVE_SCOPE,prompt:'select_account',callback:async r=>{if(r.error)return reject(new Error(r.error_description||r.error));this.token=r.access_token;this.expiresAt=Date.now()+(Number(r.expires_in||3600)*1000);try{await this.loadUser();await this.ensureStructure();this.dispatchEvent(new Event('state'));resolve(this.state())}catch(e){reject(e)}}});c.requestAccessToken()})}
 disconnect(){this.token='';this.expiresAt=0;this.user=null;this.folders={};this.dispatchEvent(new Event('state'))}
 async api(url,opt={}){if(!this.connected)throw new Error('Google Drive non connecté.');const h=new Headers(opt.headers||{});h.set('Authorization','Bearer '+this.token);return jsonOrError(await fetch(url,{...opt,headers:h}))}
 async loadUser(){try{this.user=await this.api('https://www.googleapis.com/oauth2/v3/userinfo')}catch{this.user=null}}
 async findFolder(name,parent='root'){const q=["mimeType='application/vnd.google-apps.folder'","trashed=false","name='"+String(name).replace(/'/g,"\\'")+"'"];if(parent)q.push("'"+parent+"' in parents");const p=new URLSearchParams({q:q.join(' and '),spaces:'drive',fields:'files(id,name,webViewLink)',pageSize:'10'});const d=await this.api('https://www.googleapis.com/drive/v3/files?'+p);return d.files?.[0]||null}
 async createFolder(name,parent='root'){return this.api('https://www.googleapis.com/drive/v3/files?fields=id,name,webViewLink',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({name,mimeType:'application/vnd.google-apps.folder',parents:parent?[parent]:undefined})})}
 async ensureFolder(name,parent='root'){return(await this.findFolder(name,parent))||this.createFolder(name,parent)}
 async ensureStructure(){const nlab=await this.ensureFolder('nLab','root'),pdf=await this.ensureFolder('PDF Studio',nlab.id);for(const n of ['Documents','Signatures','Exports','Releases'])this.folders[n.toLowerCase()]=await this.ensureFolder(n,pdf.id);this.folders.root=pdf;this.dispatchEvent(new Event('state'));return this.folders}
 async download(id,name='document.pdf',mime='application/pdf'){const r=await fetch('https://www.googleapis.com/drive/v3/files/'+encodeURIComponent(id)+'?alt=media',{headers:{Authorization:'Bearer '+this.token}});if(!r.ok)throw new Error('Drive HTTP '+r.status);return new File([await r.blob()],name,{type:mime})}
 async uploadToFolderId(blob,name,parentId){const boundary='-------nlab'+Math.random().toString(16).slice(2),meta=JSON.stringify({name,parents:[parentId]}),body=new Blob(['--'+boundary+'\r\nContent-Type: application/json; charset=UTF-8\r\n\r\n',meta,'\r\n--'+boundary+'\r\nContent-Type: '+(blob.type||'application/octet-stream')+'\r\n\r\n',blob,'\r\n--'+boundary+'--'],{type:'multipart/related; boundary='+boundary});return jsonOrError(await fetch('https://www.googleapis.com/upload/drive/v3/files?uploadType=multipart&fields=id,name,webViewLink',{method:'POST',headers:{Authorization:'Bearer '+this.token},body}))}
 async upload(blob,name,folder='exports'){await this.ensureStructure();const f=this.folders[folder];if(!f)throw new Error('Dossier Drive inconnu : '+folder);return this.uploadToFolderId(blob,name,f.id)}
 async picker({folders=false,multiple=false}={}){if(!this.connected)throw new Error('Google Drive non connecté.');const apiKey=String(this.config.apiKey||'').trim(),appId=String(this.config.appId||'').trim();if(!apiKey||!window.gapi)throw new Error('Google Picker nécessite une API Key Google dans la configuration.');await new Promise((res,rej)=>gapi.load('picker',{callback:res,onerror:rej}));return new Promise(resolve=>{let view;if(folders)view=new google.picker.DocsView(google.picker.ViewId.FOLDERS).setIncludeFolders(true).setSelectFolderEnabled(true);else view=new google.picker.DocsView().setMimeTypes('application/pdf,application/zip,image/png,image/jpeg,application/vnd.openxmlformats-officedocument.wordprocessingml.document,application/vnd.oasis.opendocument.text,text/plain');let b=new google.picker.PickerBuilder().addView(view).setOAuthToken(this.token).setDeveloperKey(apiKey).setCallback(data=>{if(data.action===google.picker.Action.PICKED)resolve(multiple?(data.docs||[]):(data.docs?.[0]||null));if(data.action===google.picker.Action.CANCEL)resolve(multiple?[]:null)});if(multiple)b=b.enableFeature(google.picker.Feature.MULTISELECT_ENABLED);if(appId)b.setAppId(appId);b.build().setVisible(true)})}
 async pickAndDownload(){const d=await this.picker({folders:false});if(!d)return null;return this.download(d.id,d.name||'drive-file.pdf',d.mimeType||'application/pdf')}
 async pickManyAndDownload(){const docs=await this.picker({folders:false,multiple:true}),out=[];for(const d of docs||[])out.push(await this.download(d.id,d.name||'drive-file',d.mimeType||'application/octet-stream'));return out}
 async pickFolder(){return this.picker({folders:true,multiple:false})}
}
export const GOOGLE_DRIVE_SCOPE=DRIVE_SCOPE;
