export function rowsToObjects(rows){const a=rows||[],head=a[0]||[];return a.slice(1).map(r=>Object.fromEntries(head.map((h,i)=>[String(h||'col_'+(i+1)),r[i]??''])))}
export function objectsToRows(items){const list=Array.isArray(items)?items:(items?.records||[items]),keys=[...new Set(list.flatMap(r=>Object.keys(r||{})))];return[keys,...list.map(r=>keys.map(k=>r?.[k]??''))]}
export function parseCsv(text,{delimiter='',header=true,dynamicTyping=true}={}){if(globalThis.Papa){const r=Papa.parse(String(text??''),{header,skipEmptyLines:true,dynamicTyping,delimiter});if(r.errors?.length)console.warn(r.errors);return r.data}const lines=String(text??'').split(/\r?\n/).filter(Boolean),sep=delimiter||(/[;\t|]/.exec(lines[0]||'')?.[0]||','),rows=lines.map(l=>l.split(sep));return header?rowsToObjects(rows):rows}
export function toCsv(data,{delimiter=';',bom=true}={}){const rows=Array.isArray(data)&&Array.isArray(data[0])?data:objectsToRows(data),q=v=>'"'+String(v??'').replaceAll('"','""')+'"';return(bom?'\ufeff':'')+rows.map(r=>r.map(q).join(delimiter)).join('\r\n')}
export function filterRows(rows,{query='',column='',value=''}={}){const q=String(query||'').trim().toLowerCase(),v=String(value||'').trim().toLowerCase();return(rows||[]).filter(r=>{if(q&&!Object.values(r||{}).some(x=>String(x??'').toLowerCase().includes(q)))return false;if(v){const vals=column?[r?.[column]]:Object.values(r||{});if(!vals.some(x=>String(x??'').toLowerCase().includes(v)))return false}return true})}
export function sortRows(rows,column,direction='asc'){if(!column)return[...(rows||[])];const dir=direction==='desc'?-1:1;return[...(rows||[])].sort((a,b)=>{const av=a?.[column],bv=b?.[column],an=Number(av),bn=Number(bv);let x;if(av==null&&bv==null)x=0;else if(av==null)x=-1;else if(bv==null)x=1;else if(!Number.isNaN(an)&&!Number.isNaN(bn))x=an-bn;else x=String(av).localeCompare(String(bv),'fr',{numeric:true,sensitivity:'base'});return x*dir})}
export function workbookFromObjects(data,{sheetName='Data'}={}){if(!globalThis.XLSX)throw new Error('XLSX indisponible');const wb=XLSX.utils.book_new(),ws=XLSX.utils.json_to_sheet(data||[]);XLSX.utils.book_append_sheet(wb,ws,sheetName);return wb}
export function workbookFromRows(rows,{sheetName='Data'}={}){if(!globalThis.XLSX)throw new Error('XLSX indisponible');const wb=XLSX.utils.book_new(),ws=XLSX.utils.aoa_to_sheet(rows||[]);XLSX.utils.book_append_sheet(wb,ws,sheetName);return wb}
export function workbookToObjects(wb,sheetName=null){if(!globalThis.XLSX)throw new Error('XLSX indisponible');const name=sheetName||wb?.SheetNames?.[0];return name&&wb.Sheets?.[name]?XLSX.utils.sheet_to_json(wb.Sheets[name],{defval:''}):[]}
export function workbookToRows(wb,sheetName=null){if(!globalThis.XLSX)throw new Error('XLSX indisponible');const name=sheetName||wb?.SheetNames?.[0];return name&&wb.Sheets?.[name]?XLSX.utils.sheet_to_json(wb.Sheets[name],{header:1,defval:''}):[]}

export async function readWorkbook(file){if(!globalThis.XLSX)throw new Error('XLSX indisponible');return XLSX.read(await file.arrayBuffer(),{type:'array',cellDates:true})}
export function workbookFromCsv(text,{delimiter=''}={}){if(!globalThis.XLSX)throw new Error('XLSX indisponible');return XLSX.read(String(text??''),{type:'string',FS:delimiter||undefined})}
export function workbookFromJson(data,{sheetName='Data'}={}){return workbookFromObjects(Array.isArray(data)?data:(data?.records||[data]),{sheetName})}
export function workbookBlob(wb,bookType='xlsx'){if(!globalThis.XLSX)throw new Error('XLSX indisponible');const arr=XLSX.write(wb,{bookType,type:'array'});const mime=bookType==='ods'?'application/vnd.oasis.opendocument.spreadsheet':'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet';return new Blob([arr],{type:mime})}
