import{formatBytes,toast,setStatus,downloadBlob,uid}from'./core.js';
const ACCEPT=/\.(pdf|png|jpe?g|webp|gif|bmp|docx|zip)$/i;
async function walkDirectory(handle,prefix=''){const out=[];for await(const [name,h] of handle.entries()){const rel=prefix?prefix+'/'+name:name;if(h.kind==='directory')out.push(...await walkDirectory(h,rel));else if(ACCEPT.test(name)){const file=await h.getFile();out.push({id:uid('file'),file,name:file.name,relativePath:rel,handle:h,parent:handle,checked:true})}}return out}
async function unpackZip(file,prefix=''){if(!window.JSZip)throw new Error('JSZip indisponible');const zip=await JSZip.loadAsync(file);const out=[];for(const entry of Object.values(zip.files)){if(entry.dir||!ACCEPT.test(entry.name)||/\.zip$/i.test(entry.name))continue;const blob=await entry.async('blob'),name=entry.name.split('/').pop();out.push({id:uid('zip'),file:new File([blob],name,{type:blob.type,lastModified:Date.now()}),name,relativePath:(prefix?prefix+'/':'')+entry.name,virtualZip:file.name,checked:true})}return out}
export class FileWorkspace{
 constructor({queueEl,onOpen}={}){this.queueEl=queueEl;this.onOpen=onOpen;this.items=[];this.currentId=null;this.sourceHandle=null;this.outputHandle=null;this.history=JSON.parse(localStorage.getItem('nlab-studio-v1-history')||'[]')}
 async chooseDirectory(){if(!window.showDirectoryPicker)throw new Error('Sélection de dossier non prise en charge par ce navigateur');this.sourceHandle=await showDirectoryPicker({mode:'read'});this.items=await walkDirectory(this.sourceHandle);this.afterLoad('Dossier '+this.sourceHandle.name);return this.items}
 async chooseFiles(files){const raw=[...files],out=[];for(const file of raw){if(!ACCEPT.test(file.name))continue;if(/\.zip$/i.test(file.name))out.push(...await unpackZip(file));else out.push({id:uid('file'),file,name:file.name,relativePath:file.webkitRelativePath||file.name,checked:true})}this.items=out;this.afterLoad(raw.length+' fichier(s)');return this.items}
 async addFiles(files){const existing=new Set(this.items.map(x=>x.relativePath));for(const file of [...files]){if(!ACCEPT.test(file.name))continue;const add=/\.zip$/i.test(file.name)?await unpackZip(file):[{id:uid('file'),file,name:file.name,relativePath:file.webkitRelativePath||file.name,checked:true}];for(const x of add)if(!existing.has(x.relativePath)){this.items.push(x);existing.add(x.relativePath)}}this.afterLoad('Fichiers ajoutés');return this.items}
 afterLoad(label){this.currentId=this.items[0]?.id||null;this.recordHistory();this.render();setStatus(label+' · '+this.items.length+' élément(s)');if(this.current())this.onOpen?.(this.current())}
 current(){return this.items.find(x=>x.id===this.currentId)||null}
 selected(){return this.items.filter(x=>x.checked)}
 setCurrent(id){this.currentId=id;this.render();const x=this.current();if(x)this.onOpen?.(x)}
 setAll(v){this.items.forEach(x=>x.checked=v);this.render()}
 remove(id){const i=this.items.findIndex(x=>x.id===id);if(i<0)return;this.items.splice(i,1);if(this.currentId===id)this.currentId=this.items[0]?.id||null;this.render();if(this.current())this.onOpen?.(this.current())}
 recordHistory(){for(const x of this.items.slice(0,25)){const k=x.relativePath||x.name;this.history=this.history.filter(h=>h.key!==k);this.history.unshift({key:k,name:x.name,size:x.file?.size||0,time:new Date().toISOString()})}this.history=this.history.slice(0,50);localStorage.setItem('nlab-studio-v1-history',JSON.stringify(this.history))}
 render(){if(!this.queueEl)return;this.queueEl.innerHTML='';for(const x of this.items){const row=document.createElement('div');row.className='fileRow'+(x.id===this.currentId?' active':'');row.innerHTML='<input type="checkbox" '+(x.checked?'checked':'')+'><button type="button" title="'+(x.relativePath||x.name).replace(/"/g,'&quot;')+'">'+x.name+'</button><small>'+formatBytes(x.file?.size||0)+'</small>';row.querySelector('input').onchange=e=>x.checked=e.target.checked;row.querySelector('button').onclick=()=>this.setCurrent(x.id);this.queueEl.append(row)}}
 async chooseOutputDirectory(){if(!window.showDirectoryPicker)throw new Error('Sélection de dossier non prise en charge');this.outputHandle=await showDirectoryPicker({mode:'readwrite'});return this.outputHandle}
 async writableRoot(mode='manual'){if(mode==='same-source'&&this.sourceHandle)return this.sourceHandle;if(this.outputHandle)return this.outputHandle;return null}
 async routeDirectory(mode,{operationFolder='TRAITEMENT',date=new Date(),granularity='month'}={}){let root=await this.writableRoot(mode);if(!root)return null;if(mode==='subfolder')return root.getDirectoryHandle(operationFolder||'TRAITEMENT',{create:true});if(mode==='archive-date'){const y=String(date.getFullYear()),m=String(date.getMonth()+1).padStart(2,'0'),w=isoWeek(date);let d=await root.getDirectoryHandle(y,{create:true});d=await d.getDirectoryHandle(granularity==='week'?'Semaine '+w:m,{create:true});return d}return root}
 async writeBlob(blob,name,{mode='download',operationFolder='TRAITEMENT',granularity='month'}={}){try{if(mode!=='download'){const dir=await this.routeDirectory(mode,{operationFolder,granularity});if(dir){const fh=await dir.getFileHandle(name,{create:true}),w=await fh.createWritable();await w.write(blob);await w.close();toast('Enregistré : '+name);return{kind:'filesystem',name}}}downloadBlob(blob,name);toast('Téléchargé : '+name);return{kind:'download',name}}catch(e){downloadBlob(blob,name);toast('Repli téléchargement : '+name);return{kind:'download',name,error:String(e.message||e)}}}
}
function isoWeek(d){const x=new Date(Date.UTC(d.getFullYear(),d.getMonth(),d.getDate()));x.setUTCDate(x.getUTCDate()+4-(x.getUTCDay()||7));const y=new Date(Date.UTC(x.getUTCFullYear(),0,1));return String(Math.ceil((((x-y)/86400000)+1)/7)).padStart(2,'0')}
