import{formatBytes,toast,setStatus,downloadBlob,uid}from'./core.js';
const ACCEPT=/\.(pdf|png|jpe?g|webp|gif|bmp|docx|odt|txt|zip)$/i;
function openHandleDb(){return new Promise((res,rej)=>{const r=indexedDB.open('nlab-studio-v1-handles',1);r.onupgradeneeded=()=>r.result.createObjectStore('handles');r.onsuccess=()=>res(r.result);r.onerror=()=>rej(r.error)})}
async function saveHandle(key,handle){try{const db=await openHandleDb(),tx=db.transaction('handles','readwrite');tx.objectStore('handles').put(handle,key);await new Promise((res,rej)=>{tx.oncomplete=res;tx.onerror=()=>rej(tx.error)});db.close()}catch{}}
async function getHandle(key){try{const db=await openHandleDb(),tx=db.transaction('handles','readonly'),r=tx.objectStore('handles').get(key),v=await new Promise((res,rej)=>{r.onsuccess=()=>res(r.result);r.onerror=()=>rej(r.error)});db.close();return v||null}catch{return null}}
async function ensurePermission(handle,mode='read'){if(!handle)return false;const opt={mode};if((await handle.queryPermission?.(opt))==='granted')return true;return(await handle.requestPermission?.(opt))==='granted'}
async function walkDirectory(handle,prefix=''){const out=[];for await(const [name,h] of handle.entries()){const rel=prefix?prefix+'/'+name:name;if(h.kind==='directory')out.push(...await walkDirectory(h,rel));else if(ACCEPT.test(name)){const file=await h.getFile();out.push({id:uid('file'),file,name:file.name,relativePath:rel,handle:h,parent:handle,checked:true})}}return out}
async function unpackZip(file,prefix=''){if(!window.JSZip)throw new Error('JSZip indisponible');const zip=await JSZip.loadAsync(file);const out=[];for(const entry of Object.values(zip.files)){if(entry.dir||!ACCEPT.test(entry.name)||/\.zip$/i.test(entry.name))continue;const blob=await entry.async('blob'),name=entry.name.split('/').pop();out.push({id:uid('zip'),file:new File([blob],name,{type:blob.type,lastModified:Date.now()}),name,relativePath:(prefix?prefix+'/':'')+entry.name,virtualZip:file.name,checked:true})}return out}
export class FileWorkspace{
 constructor({queueEl,onOpen,onSelectionChange,onLoad}={}){this.queueEl=queueEl;this.onOpen=onOpen;this.onSelectionChange=onSelectionChange;this.onLoad=onLoad;this.items=[];this.currentId=null;this.sourceHandle=null;this.outputHandle=null;this.history=JSON.parse(localStorage.getItem('nlab-studio-v1-history')||'[]')}
 async chooseDirectory(){if(!window.showDirectoryPicker)throw new Error('Sélection de dossier non prise en charge par ce navigateur');this.sourceHandle=await showDirectoryPicker({mode:'read'});await saveHandle('source',this.sourceHandle);this.items=await walkDirectory(this.sourceHandle);this.afterLoad('Dossier '+this.sourceHandle.name);return this.items}
 async chooseFiles(files){this.sourceHandle=null;const raw=[...files],out=[];for(const file of raw){if(!ACCEPT.test(file.name))continue;if(/\.zip$/i.test(file.name))out.push(...await unpackZip(file));else out.push({id:uid('file'),file,name:file.name,relativePath:file.webkitRelativePath||file.name,checked:true})}this.items=out;this.afterLoad(raw.length+' fichier(s)');return this.items}
 async addFiles(files){const existing=new Set(this.items.map(x=>x.relativePath));for(const file of [...files]){if(!ACCEPT.test(file.name))continue;const add=/\.zip$/i.test(file.name)?await unpackZip(file):[{id:uid('file'),file,name:file.name,relativePath:file.webkitRelativePath||file.name,checked:true}];for(const x of add)if(!existing.has(x.relativePath)){this.items.push(x);existing.add(x.relativePath)}}this.afterLoad('Fichiers ajoutés');return this.items}
 afterLoad(label){this.currentId=this.items[0]?.id||null;this.recordHistory();this.render();setStatus(label+' · '+this.items.length+' élément(s)');this.onLoad?.(this.items);this.onSelectionChange?.(this.selected(),this.items);if(this.current())this.onOpen?.(this.current())}
 current(){return this.items.find(x=>x.id===this.currentId)||null}
 currentIndex(){return this.items.findIndex(x=>x.id===this.currentId)}
 selected(){return this.items.filter(x=>x.checked)}
 previous(){if(!this.items.length)return null;let i=this.currentIndex();if(i<0)i=0;i=(i-1+this.items.length)%this.items.length;this.setCurrent(this.items[i].id);return this.current()}
 next(){if(!this.items.length)return null;let i=this.currentIndex();if(i<0)i=-1;i=(i+1)%this.items.length;this.setCurrent(this.items[i].id);return this.current()}
 sort(mode='name',direction=1){const dir=direction<0?-1:1,ext=n=>(String(n||'').match(/\.([^.]+)$/)?.[1]||'').toLowerCase(),cmp=(a,b)=>{if(mode==='size')return((a.file?.size||0)-(b.file?.size||0))*dir;if(mode==='type')return ext(a.name).localeCompare(ext(b.name),'fr')*dir;if(mode==='path')return String(a.relativePath||a.name).localeCompare(String(b.relativePath||b.name),'fr')*dir;if(mode==='pages')return((a.meta?.pages||0)-(b.meta?.pages||0))*dir;return String(a.name).localeCompare(String(b.name),'fr')*dir};this.items.sort(cmp);this.render();return this.items}
 setCurrent(id){this.currentId=id;this.render();const x=this.current();if(x)this.onOpen?.(x)}
 setAll(v){this.items.forEach(x=>x.checked=v);this.render();this.onSelectionChange?.(this.selected(),this.items)}
 remove(id){const i=this.items.findIndex(x=>x.id===id);if(i<0)return;this.items.splice(i,1);if(this.currentId===id)this.currentId=this.items[0]?.id||null;this.render();this.onSelectionChange?.(this.selected(),this.items);if(this.current())this.onOpen?.(this.current())}
 recordHistory(){for(const x of this.items.slice(0,25)){const k=x.relativePath||x.name;this.history=this.history.filter(h=>h.key!==k);this.history.unshift({key:k,name:x.name,size:x.file?.size||0,time:new Date().toISOString()})}this.history=this.history.slice(0,50);localStorage.setItem('nlab-studio-v1-history',JSON.stringify(this.history))}
 render(){if(!this.queueEl)return;this.queueEl.innerHTML='';for(const x of this.items){const row=document.createElement('div');row.className='fileRow'+(x.id===this.currentId?' active':'');row.innerHTML='<input type="checkbox" '+(x.checked?'checked':'')+'><button type="button" title="'+(x.relativePath||x.name).replace(/"/g,'&quot;')+'">'+x.name+'</button><small>'+formatBytes(x.file?.size||0)+'</small>';row.querySelector('input').onchange=e=>{x.checked=e.target.checked;this.onSelectionChange?.(this.selected(),this.items)};row.querySelector('button').onclick=()=>this.setCurrent(x.id);this.queueEl.append(row)}}
 async chooseOutputDirectory(){if(!window.showDirectoryPicker)throw new Error('Sélection de dossier non prise en charge');this.outputHandle=await showDirectoryPicker({mode:'readwrite'});await saveHandle('output',this.outputHandle);return this.outputHandle}
 async loadLastSource(){const h=await getHandle('source');if(!h||!(await ensurePermission(h,'read')))throw new Error('Dernière source indisponible ou autorisation refusée');this.sourceHandle=h;this.items=await walkDirectory(h);this.afterLoad('Dossier mémorisé '+h.name);return h}
 async loadLastOutput(){const h=await getHandle('output');if(!h||!(await ensurePermission(h,'readwrite')))throw new Error('Dernière sortie indisponible ou autorisation refusée');this.outputHandle=h;return h}
 async writableRoot(mode='manual'){if(String(mode).startsWith('same-source')&&this.sourceHandle)return this.sourceHandle;if(this.outputHandle)return this.outputHandle;return null}
 async routeDirectory(mode,{operationFolder='TRAITEMENT',date=new Date(),granularity='month',pathTemplate=''}={}){let root=await this.writableRoot(mode);if(!root)return null;if(mode==='subfolder')return root.getDirectoryHandle(operationFolder||'TRAITEMENT',{create:true});if(mode==='archive-date'){const y=String(date.getFullYear()),m=String(date.getMonth()+1).padStart(2,'0'),w=isoWeek(date);let d=await root.getDirectoryHandle(y,{create:true});d=await d.getDirectoryHandle(granularity==='week'?'Semaine '+w:m,{create:true});return d}if(mode==='custom-path'||mode==='same-source-custom'){let d=root;for(const raw of String(pathTemplate||'').split(/[\\/]+/)){const part=raw.trim().replace(/[<>:"|?*\x00-\x1F]/g,'_');if(part)d=await d.getDirectoryHandle(part,{create:true})}return d}return root}
 async writeBlob(blob,name,{mode='download',operationFolder='TRAITEMENT',granularity='month',pathTemplate=''}={}){try{if(mode!=='download'){const dir=await this.routeDirectory(mode,{operationFolder,granularity,pathTemplate});if(dir){const fh=await dir.getFileHandle(name,{create:true}),w=await fh.createWritable();await w.write(blob);await w.close();toast('Enregistré : '+name);return{kind:'filesystem',name}}}downloadBlob(blob,name);toast('Téléchargé : '+name);return{kind:'download',name}}catch(e){downloadBlob(blob,name);toast('Repli téléchargement : '+name);return{kind:'download',name,error:String(e.message||e)}}}
}
function isoWeek(d){const x=new Date(Date.UTC(d.getFullYear(),d.getMonth(),d.getDate()));x.setUTCDate(x.getUTCDate()+4-(x.getUTCDay()||7));const y=new Date(Date.UTC(x.getUTCFullYear(),0,1));return String(Math.ceil((((x-y)/86400000)+1)/7)).padStart(2,'0')}

export function renderSelectedFilesSummary(workspace,{countEl=null,summaryEl=null,limit=12}={}){
 const selected=workspace?.selected?.()||[],all=workspace?.items||[];
 const count=typeof countEl==='string'?document.querySelector(countEl):countEl,summary=typeof summaryEl==='string'?document.querySelector(summaryEl):summaryEl;
 if(count)count.textContent=selected.length+' / '+all.length;
 if(summary)summary.textContent=selected.length?selected.slice(0,limit).map(x=>'✓ '+x.name).join('\n')+(selected.length>limit?'\n… +'+(selected.length-limit):''):'Aucun fichier sélectionné.';
 return{selected:selected.length,total:all.length}
}
